// <auto-generated>
// Generated from ActivateServiceOperation
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class ActivateServiceOperationRepository
{
    private readonly TestDbContext _ctx;

    public ActivateServiceOperationRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<ActivateServiceOperationOutput>> ExecuteAsync(ActivateServiceOperationInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<ActivateServiceOperationOutput>(
                    "[dbo].[usp_ActivateServiceOperation]",
                new DataParameter("@OperationId", input.OperationId),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@RecordVersion", input.RecordVersion)
                )).ToList();
                return RepositoryResult<ActivateServiceOperationOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<ActivateServiceOperationOutput>.Fail(ex.Message);
        }
    }
}