// <auto-generated>
// Generated from CreateServiceApplication
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateServiceApplicationRepository
{
    private readonly TestDbContext _ctx;

    public CreateServiceApplicationRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateServiceApplicationOutput>> ExecuteAsync(CreateServiceApplicationInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateServiceApplicationOutput>(
                    "[dbo].[usp_CreateServiceApplication]",
                new DataParameter("@ServiceType", input.ServiceType),
                new DataParameter("@ServiceAppAuthenticationId", input.ServiceAppAuthenticationId),
                new DataParameter("@Name", input.Name),
                new DataParameter("@BaseUrl", input.BaseUrl),
                new DataParameter("@DefinitionType", input.DefinitionType),
                new DataParameter("@DefinitionRelativeUrl", input.DefinitionRelativeUrl),
                new DataParameter("@HealthcheckRelativeUrl", input.HealthcheckRelativeUrl),
                new DataParameter("@Description", input.Description),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateServiceApplicationOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateServiceApplicationOutput>.Fail(ex.Message);
        }
    }
}