// <auto-generated>
// Generated from CreateTestSuiteExecutionAudit
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateTestSuiteExecutionAuditRepository
{
    private readonly TestDbContext _ctx;

    public CreateTestSuiteExecutionAuditRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateTestSuiteExecutionAuditOutput>> ExecuteAsync(CreateTestSuiteExecutionAuditInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateTestSuiteExecutionAuditOutput>(
                    "[dbo].[usp_CreateTestSuiteExecutionAudit]",
                new DataParameter("@ServiceTestSuiteId", input.ServiceTestSuiteId),
                new DataParameter("@ExecutionStatus", input.ExecutionStatus),
                new DataParameter("@ExecutionDetails", input.ExecutionDetails),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateTestSuiteExecutionAuditOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateTestSuiteExecutionAuditOutput>.Fail(ex.Message);
        }
    }
}