// <auto-generated>
// Generated from CreateServiceTestCase
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateServiceTestCaseRepository
{
    private readonly TestDbContext _ctx;

    public CreateServiceTestCaseRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateServiceTestCaseOutput>> ExecuteAsync(CreateServiceTestCaseInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateServiceTestCaseOutput>(
                    "[dbo].[usp_CreateServiceTestCase]",
                new DataParameter("@Name", input.Name),
                new DataParameter("@ServiceRequestFileId", input.ServiceRequestFileId),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateServiceTestCaseOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateServiceTestCaseOutput>.Fail(ex.Message);
        }
    }
}