// <auto-generated>
// Generated from CreateSoapNamespace
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateSoapNamespaceRepository
{
    private readonly TestDbContext _ctx;

    public CreateSoapNamespaceRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateSoapNamespaceOutput>> ExecuteAsync(CreateSoapNamespaceInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateSoapNamespaceOutput>(
                    "[dbo].[usp_CreateSoapNamespace]",
                new DataParameter("@ServiceOperationSchemaId", input.ServiceOperationSchemaId),
                new DataParameter("@CompressedContent", input.CompressedContent),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@ContentHash", input.ContentHash),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateSoapNamespaceOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateSoapNamespaceOutput>.Fail(ex.Message);
        }
    }
}