// <auto-generated>
// Generated from CreateServiceOperationSchema
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateServiceOperationSchemaRepository
{
    private readonly TestDbContext _ctx;

    public CreateServiceOperationSchemaRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateServiceOperationSchemaOutput>> ExecuteAsync(CreateServiceOperationSchemaInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateServiceOperationSchemaOutput>(
                    "[dbo].[usp_CreateServiceOperationSchema]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@OperationName", input.OperationName),
                new DataParameter("@InputRootElementName", input.InputRootElementName),
                new DataParameter("@OutputRootElementName", input.OutputRootElementName),
                new DataParameter("@TargetNamespace", input.TargetNamespace),
                new DataParameter("@CompressedContent", input.CompressedContent),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@ContentHash", input.ContentHash),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateServiceOperationSchemaOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateServiceOperationSchemaOutput>.Fail(ex.Message);
        }
    }
}