// <auto-generated>
// Generated from CreateServiceOperation
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class CreateServiceOperationRepository
{
    private readonly TestDbContext _ctx;

    public CreateServiceOperationRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateServiceOperationOutput>> ExecuteAsync(CreateServiceOperationInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateServiceOperationOutput>(
                    "[dbo].[usp_CreateServiceOperation]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@OperationName", input.OperationName),
                new DataParameter("@EndpointOrAction", input.EndpointOrAction),
                new DataParameter("@HttpMethod", input.HttpMethod),
                new DataParameter("@Description", input.Description),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateServiceOperationOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateServiceOperationOutput>.Fail(ex.Message);
        }
    }
}