// <auto-generated>
// Generated from GetServiceOperations
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class GetServiceOperationsRepository
{
    private readonly TestDbContext _ctx;

    public GetServiceOperationsRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetServiceOperationsOutput>>> ExecuteAsync(GetServiceOperationsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetServiceOperationsOutput>(
                    "[dbo].[usp_GetServiceOperations]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@IncludeInactive", input.IncludeInactive),
                new DataParameter("@OperationName", input.OperationName)
                )).ToList();
                return RepositoryResult<List<GetServiceOperationsOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetServiceOperationsOutput>>.Fail(ex.Message);
        }
    }
}