// <auto-generated>
// Generated from GetServiceResponseFilesByRequest
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class GetServiceResponseFilesByRequestRepository
{
    private readonly TestDbContext _ctx;

    public GetServiceResponseFilesByRequestRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetServiceResponseFilesByRequestOutput>>> ExecuteAsync(GetServiceResponseFilesByRequestInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetServiceResponseFilesByRequestOutput>(
                    "[dbo].[usp_GetServiceResponseFilesByRequest]",
                new DataParameter("@RequestFileId", input.RequestFileId),
                new DataParameter("@IncludeInactive", input.IncludeInactive)
                )).ToList();
                return RepositoryResult<List<GetServiceResponseFilesByRequestOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetServiceResponseFilesByRequestOutput>>.Fail(ex.Message);
        }
    }
}