// <auto-generated>
// Generated from GetServiceDefinitionSync
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class GetServiceDefinitionSyncRepository
{
    private readonly TestDbContext _ctx;

    public GetServiceDefinitionSyncRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetServiceDefinitionSyncOutput>>> ExecuteAsync(GetServiceDefinitionSyncInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetServiceDefinitionSyncOutput>(
                    "[dbo].[usp_GetServiceDefinitionSync]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@IncludeContent", input.IncludeContent)
                )).ToList();
                return RepositoryResult<List<GetServiceDefinitionSyncOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetServiceDefinitionSyncOutput>>.Fail(ex.Message);
        }
    }
}