// <auto-generated>
// Generated from GetServiceOperationSchemas
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class GetServiceOperationSchemasRepository
{
    private readonly TestDbContext _ctx;

    public GetServiceOperationSchemasRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetServiceOperationSchemasOutput>>> ExecuteAsync(GetServiceOperationSchemasInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetServiceOperationSchemasOutput>(
                    "[dbo].[usp_GetServiceOperationSchemas]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@OperationName", input.OperationName),
                new DataParameter("@IncludeContent", input.IncludeContent)
                )).ToList();
                return RepositoryResult<List<GetServiceOperationSchemasOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetServiceOperationSchemasOutput>>.Fail(ex.Message);
        }
    }
}