// <auto-generated>
// Generated from GetServiceResponseFileChain
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class GetServiceResponseFileChainRepository
{
    private readonly TestDbContext _ctx;

    public GetServiceResponseFileChainRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetServiceResponseFileChainOutput>>> ExecuteAsync(GetServiceResponseFileChainInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetServiceResponseFileChainOutput>(
                    "[dbo].[usp_GetServiceResponseFileChain]",
                new DataParameter("@ResponseFileId", input.ResponseFileId),
                new DataParameter("@IncludeData", input.IncludeData)
                )).ToList();
                return RepositoryResult<List<GetServiceResponseFileChainOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetServiceResponseFileChainOutput>>.Fail(ex.Message);
        }
    }
}