// <auto-generated>
// Generated from InsertServiceResponseFileEmbedding
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class InsertServiceResponseFileEmbeddingRepository
{
    private readonly TestDbContext _ctx;

    public InsertServiceResponseFileEmbeddingRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<InsertServiceResponseFileEmbeddingOutput>> ExecuteAsync(InsertServiceResponseFileEmbeddingInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<InsertServiceResponseFileEmbeddingOutput>(
                    "[dbo].[usp_InsertServiceResponseFileEmbedding]",
                new DataParameter("@ServiceResponseFileId", input.ServiceResponseFileId),
                new DataParameter("@CompressedData", input.CompressedData),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@FileFormat", input.FileFormat),
                new DataParameter("@Name", input.Name),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<InsertServiceResponseFileEmbeddingOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<InsertServiceResponseFileEmbeddingOutput>.Fail(ex.Message);
        }
    }
}