// <auto-generated>
// Generated from InsertServiceDefinitionSync
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class InsertServiceDefinitionSyncRepository
{
    private readonly TestDbContext _ctx;

    public InsertServiceDefinitionSyncRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<InsertServiceDefinitionSyncOutput>> ExecuteAsync(InsertServiceDefinitionSyncInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<InsertServiceDefinitionSyncOutput>(
                    "[dbo].[usp_InsertServiceDefinitionSync]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@CompressedContent", input.CompressedContent),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@ContentHash", input.ContentHash)
                )).ToList();
                return RepositoryResult<InsertServiceDefinitionSyncOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<InsertServiceDefinitionSyncOutput>.Fail(ex.Message);
        }
    }
}