// <auto-generated>
// Generated from InsertServiceResponseFile
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class InsertServiceResponseFileRepository
{
    private readonly TestDbContext _ctx;

    public InsertServiceResponseFileRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<InsertServiceResponseFileOutput>> ExecuteAsync(InsertServiceResponseFileInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<InsertServiceResponseFileOutput>(
                    "[dbo].[usp_InsertServiceResponseFile]",
                new DataParameter("@ServiceRequestFileId", input.ServiceRequestFileId),
                new DataParameter("@Name", input.Name),
                new DataParameter("@FileFormat", input.FileFormat),
                new DataParameter("@IsBaseSnapshot", input.IsBaseSnapshot),
                new DataParameter("@ParentBaseId", input.ParentBaseId),
                new DataParameter("@ParentDeltaId", input.ParentDeltaId),
                new DataParameter("@CompressedData", input.CompressedData),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@FileHash", input.FileHash),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<InsertServiceResponseFileOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<InsertServiceResponseFileOutput>.Fail(ex.Message);
        }
    }
}