// <auto-generated>
// Generated from LinkTestCaseToSuite
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class LinkTestCaseToSuiteRepository
{
    private readonly TestDbContext _ctx;

    public LinkTestCaseToSuiteRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<LinkTestCaseToSuiteOutput>> ExecuteAsync(LinkTestCaseToSuiteInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<LinkTestCaseToSuiteOutput>(
                    "[dbo].[usp_LinkTestCaseToSuite]",
                new DataParameter("@ServiceTestSuiteId", input.ServiceTestSuiteId),
                new DataParameter("@ServiceTestCaseId", input.ServiceTestCaseId),
                new DataParameter("@ExecutionOrder", input.ExecutionOrder),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<LinkTestCaseToSuiteOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<LinkTestCaseToSuiteOutput>.Fail(ex.Message);
        }
    }
}