// <auto-generated>
// Generated from LinkRuleSetToTestCase
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class LinkRuleSetToTestCaseRepository
{
    private readonly TestDbContext _ctx;

    public LinkRuleSetToTestCaseRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<LinkRuleSetToTestCaseOutput>> ExecuteAsync(LinkRuleSetToTestCaseInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<LinkRuleSetToTestCaseOutput>(
                    "[dbo].[usp_LinkRuleSetToTestCase]",
                new DataParameter("@ServiceTestCaseId", input.ServiceTestCaseId),
                new DataParameter("@RuleSetId", input.RuleSetId),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<LinkRuleSetToTestCaseOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<LinkRuleSetToTestCaseOutput>.Fail(ex.Message);
        }
    }
}