// <auto-generated>
// Generated from ToggleServiceApplicationActive
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class ToggleServiceApplicationActiveRepository
{
    private readonly TestDbContext _ctx;

    public ToggleServiceApplicationActiveRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult> ExecuteAsync(ToggleServiceApplicationActiveInput input, CancellationToken ct = default)
    {
        try
        {
                await _ctx.ExecuteProcAsync(
                    "[dbo].[usp_ToggleServiceApplicationActive]",
                new DataParameter("@PublicId", input.PublicId),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@IsActive", input.IsActive)
                );
                return RepositoryResult.Ok();
        }
        catch (Exception ex)
        {
            return RepositoryResult.Fail(ex.Message);
        }
    }
}