// <auto-generated>
// Generated from UpdateServiceTestSuite
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpdateServiceTestSuiteRepository
{
    private readonly TestDbContext _ctx;

    public UpdateServiceTestSuiteRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpdateServiceTestSuiteOutput>> ExecuteAsync(UpdateServiceTestSuiteInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpdateServiceTestSuiteOutput>(
                    "[dbo].[usp_UpdateServiceTestSuite]",
                new DataParameter("@TestSuiteId", input.TestSuiteId),
                new DataParameter("@Name", input.Name),
                new DataParameter("@Description", input.Description),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@RecordVersion", input.RecordVersion)
                )).ToList();
                return RepositoryResult<UpdateServiceTestSuiteOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpdateServiceTestSuiteOutput>.Fail(ex.Message);
        }
    }
}