// <auto-generated>
// Generated from UpdateServiceOperationSchema
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpdateServiceOperationSchemaRepository
{
    private readonly TestDbContext _ctx;

    public UpdateServiceOperationSchemaRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpdateServiceOperationSchemaOutput>> ExecuteAsync(UpdateServiceOperationSchemaInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpdateServiceOperationSchemaOutput>(
                    "[dbo].[usp_UpdateServiceOperationSchema]",
                new DataParameter("@SchemaId", input.SchemaId),
                new DataParameter("@InputRootElementName", input.InputRootElementName),
                new DataParameter("@OutputRootElementName", input.OutputRootElementName),
                new DataParameter("@TargetNamespace", input.TargetNamespace),
                new DataParameter("@CompressedContent", input.CompressedContent),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@ContentHash", input.ContentHash),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@RecordVersion", input.RecordVersion)
                )).ToList();
                return RepositoryResult<UpdateServiceOperationSchemaOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpdateServiceOperationSchemaOutput>.Fail(ex.Message);
        }
    }
}