// <auto-generated>
// Generated from UpdateServiceDefinitionSync
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpdateServiceDefinitionSyncRepository
{
    private readonly TestDbContext _ctx;

    public UpdateServiceDefinitionSyncRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpdateServiceDefinitionSyncOutput>> ExecuteAsync(UpdateServiceDefinitionSyncInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpdateServiceDefinitionSyncOutput>(
                    "[dbo].[usp_UpdateServiceDefinitionSync]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@CompressedContent", input.CompressedContent),
                new DataParameter("@UncompressedSizeBytes", input.UncompressedSizeBytes),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@ContentHash", input.ContentHash)
                )).ToList();
                return RepositoryResult<UpdateServiceDefinitionSyncOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpdateServiceDefinitionSyncOutput>.Fail(ex.Message);
        }
    }
}