// <auto-generated>
// Generated from UpdateServiceRequestFileEmbedding
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpdateServiceRequestFileEmbeddingRepository
{
    private readonly TestDbContext _ctx;

    public UpdateServiceRequestFileEmbeddingRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpdateServiceRequestFileEmbeddingOutput>> ExecuteAsync(UpdateServiceRequestFileEmbeddingInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpdateServiceRequestFileEmbeddingOutput>(
                    "[dbo].[usp_UpdateServiceRequestFileEmbedding]",
                new DataParameter("@EmbeddingId", input.EmbeddingId),
                new DataParameter("@Name", input.Name),
                new DataParameter("@FileHash", input.FileHash),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<UpdateServiceRequestFileEmbeddingOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpdateServiceRequestFileEmbeddingOutput>.Fail(ex.Message);
        }
    }
}