// <auto-generated>
// Generated from UpdateServiceOperation
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpdateServiceOperationRepository
{
    private readonly TestDbContext _ctx;

    public UpdateServiceOperationRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpdateServiceOperationOutput>> ExecuteAsync(UpdateServiceOperationInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpdateServiceOperationOutput>(
                    "[dbo].[usp_UpdateServiceOperation]",
                new DataParameter("@OperationId", input.OperationId),
                new DataParameter("@OperationName", input.OperationName),
                new DataParameter("@EndpointOrAction", input.EndpointOrAction),
                new DataParameter("@HttpMethod", input.HttpMethod),
                new DataParameter("@Description", input.Description),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@RecordVersion", input.RecordVersion)
                )).ToList();
                return RepositoryResult<UpdateServiceOperationOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpdateServiceOperationOutput>.Fail(ex.Message);
        }
    }
}