// <auto-generated>
// Generated from UpsertServiceApplication
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Models;

namespace OrbitHub.Data.Repositories.TestManagement.Repositories;

public class UpsertServiceApplicationRepository
{
    private readonly TestDbContext _ctx;

    public UpsertServiceApplicationRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UpsertServiceApplicationOutput>> ExecuteAsync(UpsertServiceApplicationInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpsertServiceApplicationOutput>(
                    "[dbo].[usp_UpsertServiceApplication]",
                new DataParameter("@PublicId", input.PublicId),
                new DataParameter("@RecordVersion", input.RecordVersion),
                new DataParameter("@ServiceType", input.ServiceType),
                new DataParameter("@ServiceAppAuthenticationId", input.ServiceAppAuthenticationId),
                new DataParameter("@Name", input.Name),
                new DataParameter("@BaseUrl", input.BaseUrl),
                new DataParameter("@DefinitionType", input.DefinitionType),
                new DataParameter("@DefinitionRelativeUrl", input.DefinitionRelativeUrl),
                new DataParameter("@HealthcheckRelativeUrl", input.HealthcheckRelativeUrl),
                new DataParameter("@Description", input.Description),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@ActivityNotes", input.ActivityNotes)
                )).ToList();
                return RepositoryResult<UpsertServiceApplicationOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UpsertServiceApplicationOutput>.Fail(ex.Message);
        }
    }
}