// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.UIManagement;

[Table("UIPages")]
public partial class UiPage
{
	/// <summary>
	/// Unique identifier for this UIPages record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related UIPages record.
	/// </summary>
	[Column("ParentId")]
	public int? ParentId { get; set; } // int

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(100)

	/// <summary>
	/// Permission key required to view this page or perform this action.
	/// </summary>
	[Column("RequiredPermissionKey")]
	public string? RequiredPermissionKey { get; set; } // nvarchar(100)

	/// <summary>
	/// Name of the feature flag that controls whether this page is visible.
	/// </summary>
	[Column("FeatureFlag")]
	public string? FeatureFlag { get; set; } // nvarchar(100)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Indicates whether this page is shown in the navigation menu.
	/// </summary>
	[Column("IsVisibleInNav")]
	public bool IsVisibleInNav { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_PermissionToUIPageMapping_UIPages backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(PermissionToUiPageMapping.UiPageId))]
	public IEnumerable<PermissionToUiPageMapping> PermissionToUiPageMappings { get; set; } = null!;

	/// <summary>
	/// FK_UIActions_UIPages_PageId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(UiAction.PageId))]
	public IEnumerable<UiAction> UiActions { get; set; } = null!;

	/// <summary>
	/// FK_UIPages_ParentId
	/// </summary>
	[Association(ThisKey = nameof(ParentId), OtherKey = nameof(Id))]
	public UiPage? Parent { get; set; }

	/// <summary>
	/// FK_UIPages_ParentId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ParentId))]
	public IEnumerable<UiPage> UiPages { get; set; } = null!;
	#endregion
}
