<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://example.com/billing" targetNamespace="http://example.com/billing">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <element name="GetUserRequest"><complexType><sequence><element name="Id" type="string"/></sequence></complexType></element>
      <element name="GetUserResponse"><complexType><sequence><element name="User" type="string"/></sequence></complexType></element>
      <element name="UpdateUserRequest"><complexType><sequence><element name="Id" type="string"/><element name="Name" type="string"/><element name="Email" type="string"/></sequence></complexType></element>
      <element name="UpdateUserResponse"><complexType><sequence><element name="Status" type="string"/></sequence></complexType></element>
    </schema>
  </wsdl:types>
  <wsdl:message name="GetUserRequest"><part name="parameters" element="tns:GetUserRequest"/></wsdl:message>
  <wsdl:message name="GetUserResponse"><part name="parameters" element="tns:GetUserResponse"/></wsdl:message>
  <wsdl:message name="UpdateUserRequest"><part name="parameters" element="tns:UpdateUserRequest"/></wsdl:message>
  <wsdl:message name="UpdateUserResponse"><part name="parameters" element="tns:UpdateUserResponse"/></wsdl:message>
  <wsdl:portType name="BillingPortType">
    <operation name="GetUser">
      <input message="tns:GetUserRequest"/>
      <output message="tns:GetUserResponse"/>
    </operation>
    <operation name="UpdateUser">
      <input message="tns:UpdateUserRequest"/>
      <output message="tns:UpdateUserResponse"/>
    </operation>
  </wsdl:portType>
  <wsdl:binding name="BillingBinding" type="tns:BillingPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetUser"><soap:operation soapAction="getUser"/><input><soap:body use="literal"/></input><output><soap:body use="literal"/></output></operation>
    <operation name="UpdateUser"><soap:operation soapAction="updateUser"/><input><soap:body use="literal"/></input><output><soap:body use="literal"/></output></operation>
  </wsdl:binding>
  <wsdl:service name="BillingService">
    <port name="BillingPort" binding="tns:BillingBinding"><soap:address location="http://example.com/billing"/></port>
  </wsdl:service>
</wsdl:definitions>
