// <auto-generated>
// Generated from v_ServiceApplicationAudit
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.CoreManagement.Views;

public class ServiceApplicationAuditView
{
    public long AuditId { get; set; }
    public string UserId { get; set; } = string.Empty;
    public string UserFullName { get; set; } = string.Empty;
    public string UserEmail { get; set; } = string.Empty;
    public string ActivityType { get; set; } = string.Empty;
    public string? ActionType { get; set; }
    public string? FeatureActivitiesJson { get; set; }
    public DateTime Timestamp { get; set; }
    public string? ServicePublicId { get; set; }
    public string? ServiceName { get; set; }
    public string? ChangeType { get; set; }
    public string? OldVersion { get; set; }
    public string? NewVersion { get; set; }
    public string? ChangeMessage { get; set; }
    public string? Notes { get; set; }
    public string ActionDescription { get; set; } = string.Empty;
    public int HoursAgo { get; set; }
    public string FormattedTimestamp { get; set; } = string.Empty;
}
