// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.CoreManagement;

[Table("UserSettings")]
public partial class UserSetting
{
	/// <summary>
	/// Unique identifier for this UserSettings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related GlobalSettings record.
	/// </summary>
	[Column("GlobalSettingId")]
	public int? GlobalSettingId { get; set; } // int

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("UserId", CanBeNull = false)]
	public string UserId { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Configured value of the setting.
	/// </summary>
	[Column("SettingValue", CanBeNull = false)]
	public string SettingValue { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime LastUpdatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_UserSettings_GlobalSettings_GlobalSettingId
	/// </summary>
	[Association(ThisKey = nameof(GlobalSettingId), OtherKey = nameof(CoreManagement.GlobalSetting.Id))]
	public GlobalSetting? GlobalSetting { get; set; }
	#endregion
}
