// <auto-generated>
// Generated from v_RuleSetContextLinks
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Views;

public class RuleSetContextLinkView
{
    public long LinkId { get; set; }
    public long RuleSetId { get; set; }
    public long RuleContextObjectId { get; set; }
    public DateTime CreatedAt { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public string WorkflowName { get; set; } = string.Empty;
    public bool? RuleSetIsActive { get; set; }
    public string? RuleSetDescription { get; set; }
    public string ContextName { get; set; } = string.Empty;
    public int? ContextRuleTypeId { get; set; }
    public string? ContextDescription { get; set; }
    public bool? ContextIsActive { get; set; }
    public string CreatedByFullName { get; set; } = string.Empty;
    public string LastUpdatedByFullName { get; set; } = string.Empty;
}
