// <auto-generated>
// Generated from v_RuleExecutionLogsWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.RuleManagement.Views;

public class RuleExecutionLogWithDetailsView
{
    public int LogId { get; set; }

    public int RuleSetId { get; set; }

    public byte[]? InputCompressedContent { get; set; }

    public int? InputUncompressedSizeBytes { get; set; }

    public string? InputContentHash { get; set; }

    public byte[]? OutputCompressedContent { get; set; }

    public int? OutputUncompressedSizeBytes { get; set; }

    public string? OutputContentHash { get; set; }

    public string? CompressionAlgorithmType { get; set; }

    public bool? IsSuccess { get; set; }

    public string? ErrorMessage { get; set; }

    public int? ExecutionTimeMs { get; set; }

    public DateTime ExecutedAt { get; set; }

    public string ExecutedBy { get; set; } = string.Empty;

    public string WorkflowName { get; set; } = string.Empty;

    public int? OutputTypeId { get; set; }

    public string? RuleSetVersion { get; set; }

    public string? RuleSetDescription { get; set; }

    public string ExecutedByFullName { get; set; } = string.Empty;

    public string ExecutedByEmail { get; set; } = string.Empty;

    public string InputSizeHuman { get; set; } = string.Empty;

    public string OutputSizeHuman { get; set; } = string.Empty;

    public string InputHashShort { get; set; } = string.Empty;

    public string OutputHashShort { get; set; } = string.Empty;

    public string ExecutionStatus { get; set; } = string.Empty;

    public decimal? ExecutionTimeSeconds { get; set; }

    public int AgeDays { get; set; }

    public int AgeHours { get; set; }
}
