// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub REST management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RestManagement;

public partial class RestDbContext : DataConnection
{
	public RestDbContext()
	{
		InitDataContext();
	}

	public RestDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public RestDbContext(DataOptions<RestDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<RestRequestFileEntity> RestRequestFiles => this.GetTable<RestRequestFileEntity>();
}