// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.UserManagement;

[Table("UserActivities")]
public partial class UserActivity
{
	/// <summary>
	/// Unique identifier for this UserActivities record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("UserId", CanBeNull = false)]
	public string UserId { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// JSON document containing user feature activity details.
	/// </summary>
	[Column("FeatureActivitiesJson")]
	public string? FeatureActivitiesJson { get; set; } // nvarchar(max)

	/// <summary>
	/// Date and time at which the user activity was recorded.
	/// </summary>
	[Column("Timestamp")]
	public DateTime Timestamp { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_UserActivities_Users_UserId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(UserManagement.User.UserId))]
	public User User { get; set; } = null!;
	#endregion
}
