// <auto-generated>
// Generated from v_IndexingFileElementSearch
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.IndexingManagement.Views;

public class IndexingFileElementSearchView
{
    public string ElementType { get; set; } = string.Empty;

    public long ElementId { get; set; }

    public string? ElementName { get; set; }

    public string? KeyPath { get; set; }

    public string? ElementValue { get; set; }

    public string? ValueType { get; set; }

    public int? RequestFileId { get; set; }

    public int? ResponseFileId { get; set; }

    public string? RequestFileName { get; set; }

    public string? ResponseFileName { get; set; }
}
