// <auto-generated>
// Generated from GetBinaryEmbeddingByHash
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.IndexingManagement;
using OrbitHub.Data.Common;
using OrbitHub.Data.IndexingManagement.Models;

namespace OrbitHub.Data.IndexingManagement.Repositories;

public class GetBinaryEmbeddingByHashRepository
{
    private readonly IndexingDbContext _ctx;

    public GetBinaryEmbeddingByHashRepository(IndexingDbContext ctx) => _ctx = ctx;

    public async Task<RepositoryResult<GetBinaryEmbeddingByHashOutput>> ExecuteAsync(GetBinaryEmbeddingByHashInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetBinaryEmbeddingByHashOutput>(
                    "[dbo].[usp_GetBinaryEmbeddingByHash]",
                new DataParameter("@FileHash", input.FileHash),
                new DataParameter("@IncludeData", input.IncludeData)
                )).ToList();
                return RepositoryResult<GetBinaryEmbeddingByHashOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<GetBinaryEmbeddingByHashOutput>.Fail(ex.Message);
        }
    }
}