// <auto-generated>
// Generated from GetBinaryEmbeddingById
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.IndexingManagement;
using OrbitHub.Data.Common;
using OrbitHub.Data.IndexingManagement.Models;

namespace OrbitHub.Data.IndexingManagement.Repositories;

public class GetBinaryEmbeddingByIdRepository
{
    private readonly IndexingDbContext _ctx;

    public GetBinaryEmbeddingByIdRepository(IndexingDbContext ctx) => _ctx = ctx;

    public async Task<RepositoryResult<GetBinaryEmbeddingByIdOutput>> ExecuteAsync(GetBinaryEmbeddingByIdInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetBinaryEmbeddingByIdOutput>(
                    "[dbo].[usp_GetBinaryEmbeddingById]",
                new DataParameter("@EmbeddingId", input.EmbeddingId),
                new DataParameter("@IncludeData", input.IncludeData)
                )).ToList();
                return RepositoryResult<GetBinaryEmbeddingByIdOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<GetBinaryEmbeddingByIdOutput>.Fail(ex.Message);
        }
    }
}