// <auto-generated>
// Generated from GetIndexingStatistics
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.IndexingManagement;
using OrbitHub.Data.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Models;

namespace OrbitHub.Data.IndexingManagement.Repositories;

public class GetIndexingStatisticsRepository
{
    private readonly IndexingDbContext _ctx;

    public GetIndexingStatisticsRepository(IndexingDbContext ctx) => _ctx = ctx;

    public async Task<RepositoryResult<List<GetIndexingStatisticsOutput>>> ExecuteAsync(GetIndexingStatisticsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetIndexingStatisticsOutput>(
                    "[dbo].[usp_GetIndexingStatistics]")).ToList();
                return RepositoryResult<List<GetIndexingStatisticsOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetIndexingStatisticsOutput>>.Fail(ex.Message);
        }
    }
}