// <auto-generated>
// Generated from v_BinaryEmbeddingsByFormat
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class BinaryEmbeddingsByFormatViewRepository
{
    private readonly IndexingDbContext _ctx;

    public BinaryEmbeddingsByFormatViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<BinaryEmbeddingsByFormatView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<BinaryEmbeddingsByFormatView>(
                "SELECT * FROM [dbo].[v_BinaryEmbeddingsByFormat]"
            )).ToList();
            return RepositoryResult<List<BinaryEmbeddingsByFormatView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<BinaryEmbeddingsByFormatView>>.Fail(ex.Message);
        }
    }
}
