// <auto-generated>
// Generated from v_BinaryEmbeddingsByFormat
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class BinaryEmbeddingsByFormatView
{
    public string? FileFormat { get; set; }
    public int EmbeddingCount { get; set; }
    public long? TotalSize { get; set; }
    public long? AvgSize { get; set; }
    public long? MinSize { get; set; }
    public long? MaxSize { get; set; }
    public string? MostUsedCompression { get; set; }
    public string TotalSizeHuman { get; set; } = string.Empty;
}
