// <auto-generated>
// Generated from v_BinaryEmbeddingsStorageSummary
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class BinaryEmbeddingsStorageSummaryViewRepository
{
    private readonly IndexingDbContext _ctx;

    public BinaryEmbeddingsStorageSummaryViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<BinaryEmbeddingsStorageSummaryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<BinaryEmbeddingsStorageSummaryView>(
                "SELECT * FROM [dbo].[v_BinaryEmbeddingsStorageSummary]"
            )).ToList();
            return RepositoryResult<List<BinaryEmbeddingsStorageSummaryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<BinaryEmbeddingsStorageSummaryView>>.Fail(ex.Message);
        }
    }
}
