// <auto-generated>
// Generated from v_BinaryEmbeddingsStoreWithUsage
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class BinaryEmbeddingsStoreWithUsageViewRepository
{
    private readonly IndexingDbContext _ctx;

    public BinaryEmbeddingsStoreWithUsageViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<BinaryEmbeddingsStoreWithUsageView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<BinaryEmbeddingsStoreWithUsageView>(
                "SELECT * FROM [dbo].[v_BinaryEmbeddingsStoreWithUsage]"
            )).ToList();
            return RepositoryResult<List<BinaryEmbeddingsStoreWithUsageView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<BinaryEmbeddingsStoreWithUsageView>>.Fail(ex.Message);
        }
    }
}
