// <auto-generated>
// Generated from v_IndexingElementUsageStats
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class IndexingElementUsageStatsViewRepository
{
    private readonly IndexingDbContext _ctx;

    public IndexingElementUsageStatsViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<IndexingElementUsageStatsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<IndexingElementUsageStatsView>(
                "SELECT * FROM [dbo].[v_IndexingElementUsageStats]"
            )).ToList();
            return RepositoryResult<List<IndexingElementUsageStatsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<IndexingElementUsageStatsView>>.Fail(ex.Message);
        }
    }
}
