// <auto-generated>
// Generated from v_IndexingFileElementSearch
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class IndexingFileElementSearchViewRepository
{
    private readonly IndexingDbContext _ctx;

    public IndexingFileElementSearchViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<IndexingFileElementSearchView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<IndexingFileElementSearchView>(
                "SELECT * FROM [dbo].[v_IndexingFileElementSearch]"
            )).ToList();
            return RepositoryResult<List<IndexingFileElementSearchView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<IndexingFileElementSearchView>>.Fail(ex.Message);
        }
    }
}
