// <auto-generated>
// Generated from v_IndexingPendingQueue
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Views;
using OrbitHub.Data.IndexingManagement;

namespace OrbitHub.Data.Repositories.IndexingManagement.Views;

public class IndexingPendingQueueViewRepository
{
    private readonly IndexingDbContext _ctx;

    public IndexingPendingQueueViewRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<IndexingPendingQueueView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<IndexingPendingQueueView>(
                "SELECT * FROM [dbo].[v_IndexingPendingQueue]"
            )).ToList();
            return RepositoryResult<List<IndexingPendingQueueView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<IndexingPendingQueueView>>.Fail(ex.Message);
        }
    }
}
