// <auto-generated>
// Generated from DeleteUserPermission
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class DeleteUserPermissionOutput
{
    public long? UserPermissionId { get; set; }
    public string? Message { get; set; }
    public long? AuditActivityId { get; set; }
}