// <auto-generated>
// Generated from GetAvailablePermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.PermissionsManagement.Models;

public class GetAvailablePermissionsInput
{
    public string? SearchTerm { get; set; } = default!;
}