// <auto-generated>
// Generated from GetUserPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class GetUserPermissionsOutput
{
    public long? UserPermissionId { get; set; }
    public Guid? PublicId { get; set; }
    public string? UserId { get; set; }
    public long? ResourcePermissionId { get; set; }
    public bool? IsGranted { get; set; }
    public bool? IsActive { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public string? PermissionKey { get; set; }
    public string? UserFullName { get; set; }
    public string? UserEmail { get; set; }
    public string? PermissionStatus { get; set; }
    public string? StatusDescription { get; set; }
}