// <auto-generated>
// Generated from GetUserPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.PermissionsManagement.Models;

public class GetUserPermissionsInput
{
    public string? UserId { get; set; } = default!;
    public bool? IncludeInactive { get; set; } = default!;
}