// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.CoreManagement;

[Table("GlobalSettings")]
public partial class GlobalSetting
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("Category", CanBeNull = false)]
	public string Category { get; set; } = null!; // nvarchar(50)
	[Column("SettingKey", CanBeNull = false)]
	public string SettingKey { get; set; } = null!; // nvarchar(100)
	[Column("SettingValue", CanBeNull = false)]
	public string SettingValue { get; set; } = null!; // nvarchar(max)
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(500)
	[Column("DataType", CanBeNull = false)]
	public string DataType { get; set; } = null!; // varchar(20)
	[Column("IsUserOverridable")]
	public bool IsUserOverridable { get; set; } // bit
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_UserSettings_GlobalSettings_GlobalSettingId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(UserSetting.GlobalSettingId))]
	public IEnumerable<UserSetting> UserSettings { get; set; } = null!;
	#endregion
}
