// <auto-generated>
// Generated from CreateRuleContextObject
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class CreateRuleContextObjectRepository
{
    private readonly RuleDbContext _ctx;

    public CreateRuleContextObjectRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateRuleContextObjectOutput>> ExecuteAsync(CreateRuleContextObjectInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateRuleContextObjectOutput>(
                    "[dbo].[usp_CreateRuleContextObject]",
                new DataParameter("@ContextName", input.ContextName),
                new DataParameter("@RuleTypeId", input.RuleTypeId),
                new DataParameter("@Description", input.Description),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateRuleContextObjectOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateRuleContextObjectOutput>.Fail(ex.Message);
        }
    }
}