// <auto-generated>
// Generated from CreateRuleSet
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class CreateRuleSetRepository
{
    private readonly RuleDbContext _ctx;

    public CreateRuleSetRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateRuleSetOutput>> ExecuteAsync(CreateRuleSetInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateRuleSetOutput>(
                    "[dbo].[usp_CreateRuleSet]",
                new DataParameter("@WorkflowName", input.WorkflowName),
                new DataParameter("@RuleContent", input.RuleContent),
                new DataParameter("@OutputTypeId", input.OutputTypeId),
                new DataParameter("@Description", input.Description),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<CreateRuleSetOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateRuleSetOutput>.Fail(ex.Message);
        }
    }
}