// <auto-generated>
// Generated from GetRuleSetsByContext
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class GetRuleSetsByContextRepository
{
    private readonly RuleDbContext _ctx;

    public GetRuleSetsByContextRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetRuleSetsByContextOutput>>> ExecuteAsync(GetRuleSetsByContextInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetRuleSetsByContextOutput>(
                    "[dbo].[usp_GetRuleSetsByContext]",
                new DataParameter("@ContextName", input.ContextName)
                )).ToList();
                return RepositoryResult<List<GetRuleSetsByContextOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetRuleSetsByContextOutput>>.Fail(ex.Message);
        }
    }
}