// <auto-generated>
// Generated from GetRuleExecutionStatistics
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class GetRuleExecutionStatisticsRepository
{
    private readonly RuleDbContext _ctx;

    public GetRuleExecutionStatisticsRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<GetRuleExecutionStatisticsOutput>> ExecuteAsync(GetRuleExecutionStatisticsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetRuleExecutionStatisticsOutput>(
                    "[dbo].[usp_GetRuleExecutionStatistics]",
                new DataParameter("@RuleSetId", input.RuleSetId),
                new DataParameter("@DaysBack", input.DaysBack)
                )).ToList();
                return RepositoryResult<GetRuleExecutionStatisticsOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<GetRuleExecutionStatisticsOutput>.Fail(ex.Message);
        }
    }
}