// <auto-generated>
// Generated from LinkRuleSetToContextObject
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class LinkRuleSetToContextObjectRepository
{
    private readonly RuleDbContext _ctx;

    public LinkRuleSetToContextObjectRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<LinkRuleSetToContextObjectOutput>> ExecuteAsync(LinkRuleSetToContextObjectInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<LinkRuleSetToContextObjectOutput>(
                    "[dbo].[usp_LinkRuleSetToContextObject]",
                new DataParameter("@RuleSetId", input.RuleSetId),
                new DataParameter("@RuleContextObjectId", input.RuleContextObjectId),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<LinkRuleSetToContextObjectOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<LinkRuleSetToContextObjectOutput>.Fail(ex.Message);
        }
    }
}