// <auto-generated>
// Generated from LogRuleExecution
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class LogRuleExecutionRepository
{
    private readonly RuleDbContext _ctx;

    public LogRuleExecutionRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<LogRuleExecutionOutput>> ExecuteAsync(LogRuleExecutionInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<LogRuleExecutionOutput>(
                    "[dbo].[usp_LogRuleExecution]",
                new DataParameter("@RuleSetId", input.RuleSetId),
                new DataParameter("@InputCompressedContent", input.InputCompressedContent),
                new DataParameter("@InputUncompressedSizeBytes", input.InputUncompressedSizeBytes),
                new DataParameter("@InputContentHash", input.InputContentHash),
                new DataParameter("@OutputCompressedContent", input.OutputCompressedContent),
                new DataParameter("@OutputUncompressedSizeBytes", input.OutputUncompressedSizeBytes),
                new DataParameter("@OutputContentHash", input.OutputContentHash),
                new DataParameter("@CompressionAlgorithmType", input.CompressionAlgorithmType),
                new DataParameter("@IsSuccess", input.IsSuccess),
                new DataParameter("@ErrorMessage", input.ErrorMessage),
                new DataParameter("@ExecutionTimeMs", input.ExecutionTimeMs),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<LogRuleExecutionOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<LogRuleExecutionOutput>.Fail(ex.Message);
        }
    }
}