// <auto-generated>
// Generated from UnlinkRuleSetFromContextObject
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.RuleManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Models;

namespace OrbitHub.Data.Repositories.RuleManagement.Repositories;

public class UnlinkRuleSetFromContextObjectRepository
{
    private readonly RuleDbContext _ctx;

    public UnlinkRuleSetFromContextObjectRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<UnlinkRuleSetFromContextObjectOutput>> ExecuteAsync(UnlinkRuleSetFromContextObjectInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UnlinkRuleSetFromContextObjectOutput>(
                    "[dbo].[usp_UnlinkRuleSetFromContextObject]",
                new DataParameter("@LinkId", input.LinkId),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<UnlinkRuleSetFromContextObjectOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<UnlinkRuleSetFromContextObjectOutput>.Fail(ex.Message);
        }
    }
}