// <auto-generated>
// Generated from GetBinaryEmbeddingByHash
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Models;

public class GetBinaryEmbeddingByHashInput
{
    public string FileHash { get; set; } = default!;
    public bool? IncludeData { get; set; } = default!;
}