// <auto-generated>
// Generated from CreateRuleContextObject
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Models;

public class CreateRuleContextObjectOutput
{
    public int? ContextObjectId { get; set; }
    public string? ContextName { get; set; }
    public string? RuleTypeId { get; set; }
    public string? Description { get; set; }
    public bool? IsActive { get; set; }
    public DateTime? CreatedDate { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime? LastUpdatedDate { get; set; }
    public string? LastUpdatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}