// <auto-generated>
// Generated from GetRuleSetsByContext
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Models;

public class GetRuleSetsByContextOutput
{
    public int? RuleSetId { get; set; }
    public string? WorkflowName { get; set; }
    public string? RuleContent { get; set; }
    public int? OutputTypeId { get; set; }
    public bool? IsActive { get; set; }
    public string? Description { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public string? LinkedContextName { get; set; }
    public string? ContextRuleTypeId { get; set; }
}