// <auto-generated>
// Generated from GetRuleSetsByContext
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.RuleManagement.Models;

public class GetRuleSetsByContextInput
{
    public string ContextName { get; set; } = default!;
}