// <auto-generated>
// Generated from UnlinkRuleSetFromContextObject
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Models;

public class UnlinkRuleSetFromContextObjectOutput
{
    public int? LinkId { get; set; }
    public string? Message { get; set; }
    public long? AuditActivityId { get; set; }
}