// <auto-generated>
// Generated from v_RolePermissionSummary
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Views;
using OrbitHub.Data.PermissionsManagement;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Views;

public class RolePermissionSummaryViewRepository
{
    private readonly PermissionsDbContext _ctx;

    public RolePermissionSummaryViewRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<RolePermissionSummaryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<RolePermissionSummaryView>(
                "SELECT * FROM [dbo].[v_RolePermissionSummary]"
            )).ToList();
            return RepositoryResult<List<RolePermissionSummaryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<RolePermissionSummaryView>>.Fail(ex.Message);
        }
    }
}
