// <auto-generated>
// Generated from v_UserPermissionsSummary
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Views;
using OrbitHub.Data.PermissionsManagement;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Views;

public class UserPermissionsSummaryViewRepository
{
    private readonly PermissionsDbContext _ctx;

    public UserPermissionsSummaryViewRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<UserPermissionsSummaryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<UserPermissionsSummaryView>(
                "SELECT * FROM [dbo].[v_UserPermissionsSummary]"
            )).ToList();
            return RepositoryResult<List<UserPermissionsSummaryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<UserPermissionsSummaryView>>.Fail(ex.Message);
        }
    }
}
