// <auto-generated>
// Generated from v_UserPermissionsWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Views;
using OrbitHub.Data.PermissionsManagement;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Views;

public class UserPermissionsWithDetailsViewRepository
{
    private readonly PermissionsDbContext _ctx;

    public UserPermissionsWithDetailsViewRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<UserPermissionsWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<UserPermissionsWithDetailsView>(
                "SELECT * FROM [dbo].[v_UserPermissionsWithDetails]"
            )).ToList();
            return RepositoryResult<List<UserPermissionsWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<UserPermissionsWithDetailsView>>.Fail(ex.Message);
        }
    }
}
