// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub WSDL management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.WsdlManagement;

[Table("WsdlVersions")]
public partial class WsdlVersionEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("SyncRecordId")]
	public string? SyncRecordId { get; set; }

	[Column("VersionNumber")]
	public int VersionNumber { get; set; }

	[Column("Label")]
	public string? Label { get; set; }

	[Column("UploadedBy")]
	public string? UploadedBy { get; set; }

	[Column("UploadedAt")]
	public string? UploadedAt { get; set; }

	[Column("Status")]
	public string? Status { get; set; }

	[Column("Notes")]
	public string? Notes { get; set; }

	[Column("Content")]
	public string? Content { get; set; }
}