// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub WSDL management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.WsdlManagement;

[Table("WsdlSyncHistory")]
public partial class WsdlSyncHistoryEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("AppId")]
	public string? AppId { get; set; }

	[Column("AppName")]
	public string? AppName { get; set; }

	[Column("SyncRecordId")]
	public string? SyncRecordId { get; set; }

	[Column("Date")]
	public string? Date { get; set; }

	[Column("Status")]
	public string? Status { get; set; }

	[Column("Details")]
	public string? Details { get; set; }
}