// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub WSDL management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.WsdlManagement;

[Table("WsdlRecords")]
public partial class WsdlRecordEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("AppId")]
	public string? AppId { get; set; }

	[Column("AppName")]
	public string? AppName { get; set; }

	[Column("SourceType")]
	public string? SourceType { get; set; }

	[Column("SourceUrl")]
	public string? SourceUrl { get; set; }

	[Column("UploadedBy")]
	public string? UploadedBy { get; set; }

	[Column("UploadedAt")]
	public string? UploadedAt { get; set; }

	[Column("Status")]
	public string? Status { get; set; }

	[Column("WsdlContentKey")]
	public string? WsdlContentKey { get; set; }
}