// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("DirectExecutionAudit")]
public partial class DirectExecutionAudit
{
	/// <summary>
	/// Unique identifier for this DirectExecutionAudit record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime

	/// <summary>
	/// Final status of the execution.
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details captured during execution, including errors when applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionAuditResponseFileLinks_DirectExecutionAudit_DirectExecutionAuditId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionAuditResponseFileLink.DirectExecutionAuditId))]
	public IEnumerable<DirectExecutionAuditResponseFileLink> DirectExecutionAuditResponseFileLinks { get; set; } = null!;
	#endregion
}
