// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceTestSuites")]
public partial class ServiceTestSuite
{
	/// <summary>
	/// Unique identifier for this ServiceTestSuites record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(max)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestSuiteExecutionAudits_ServiceTestSuites_ServiceTestSuiteId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestSuiteExecutionAudit.ServiceTestSuiteId))]
	public IEnumerable<ServiceTestSuiteExecutionAudit> ServiceTestSuiteExecutionAudits { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuiteTestCaseLinks_ServiceTestSuites_ServiceTestSuiteId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestSuiteTestCaseLink.ServiceTestSuiteId))]
	public IEnumerable<ServiceTestSuiteTestCaseLink> ServiceTestSuiteTestCaseLinks { get; set; } = null!;
	#endregion
}
