// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceDefinitionSyncs")]
public partial class ServiceDefinitionSync
{
	/// <summary>
	/// Unique identifier for this ServiceDefinitionSyncs record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceApplications record.
	/// </summary>
	[Column("ServiceApplicationId")]
	public int ServiceApplicationId { get; set; } // int

	/// <summary>
	/// Absolute URL from which the service definition was synchronized.
	/// </summary>
	[Column("DefinitionUrl")]
	public string? DefinitionUrl { get; set; } // nvarchar(500)

	/// <summary>
	/// Compressed binary content of the synchronized WSDL, Swagger, or OpenAPI definition.
	/// </summary>
	[Column("DefinitionContent", CanBeNull = false)]
	public byte[] DefinitionContent { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the file content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// SHA-256 hash of the stored file content.
	/// </summary>
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which the service definition was synchronized.
	/// </summary>
	[Column("SyncedAt")]
	public DateTime SyncedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("SyncedBy", CanBeNull = false)]
	public string SyncedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceDefinitionSyncHistorys_ServiceDefinitionSyncs_ServiceDefinitionSyncId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceDefinitionSyncHistory.ServiceDefinitionSyncId))]
	public IEnumerable<ServiceDefinitionSyncHistory> ServiceDefinitionSyncHistorys { get; set; } = null!;

	/// <summary>
	/// FK_ServiceDefinitionSyncs_ServiceApplications_ServiceApplicationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceApplicationId), OtherKey = nameof(TestManagement.ServiceApplication.Id))]
	public ServiceApplication ServiceApplication { get; set; } = null!;

	/// <summary>
	/// FK_ServiceOperationSchemas_ServiceDefinitionSync_DefinitionSyncId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceOperationSchema.DefinitionSyncId))]
	public IEnumerable<ServiceOperationSchema> ServiceOperationSchemas { get; set; } = null!;
	#endregion
}
