// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceTestSuiteExecutionAuditTestCaseLinks")]
public partial class ServiceTestSuiteExecutionAuditTestCaseLink
{
	/// <summary>
	/// Unique identifier for this ServiceTestSuiteExecutionAuditTestCaseLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceTestSuiteExecutionAudits record.
	/// </summary>
	[Column("ServiceTestSuiteExecutionAuditId")]
	public int ServiceTestSuiteExecutionAuditId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceTestCases record.
	/// </summary>
	[Column("ServiceTestCaseId")]
	public int ServiceTestCaseId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId")]
	public int ServiceResponseFileId { get; set; } // int

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime

	/// <summary>
	/// HTTP status code returned by the service.
	/// </summary>
	[Column("HttpStatusCode")]
	public int? HttpStatusCode { get; set; } // int

	/// <summary>
	/// HTTP protocol version used for the response.
	/// </summary>
	[Column("HttpVersion")]
	public string? HttpVersion { get; set; } // nvarchar(10)

	/// <summary>
	/// Total HTTP request duration in milliseconds.
	/// </summary>
	[Column("HttpRequestDurationMs")]
	public int? HttpRequestDurationMs { get; set; } // int

	/// <summary>
	/// JSON document containing HTTP request headers.
	/// </summary>
	[Column("HttpRequestHeaders")]
	public string? HttpRequestHeaders { get; set; } // nvarchar(max)

	/// <summary>
	/// JSON document containing HTTP response headers.
	/// </summary>
	[Column("HttpResponseHeaders")]
	public string? HttpResponseHeaders { get; set; } // nvarchar(max)

	/// <summary>
	/// Content-Type header returned by the service.
	/// </summary>
	[Column("HttpContentType")]
	public string? HttpContentType { get; set; } // nvarchar(255)

	/// <summary>
	/// Content length of the service response, in bytes.
	/// </summary>
	[Column("HttpContentLength")]
	public long? HttpContentLength { get; set; } // bigint

	/// <summary>
	/// Final status of the execution.
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details captured during execution, including errors when applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestSuiteExecutionAuditTestCaseLinks_ServiceResponseFiles_ServiceResponseFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceResponseFileId), OtherKey = nameof(TestManagement.ServiceResponseFile.Id))]
	public ServiceResponseFile ServiceResponseFile { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuiteExecutionAuditTestCaseLinks_ServiceTestCases_ServiceTestCaseId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestCaseId), OtherKey = nameof(TestManagement.ServiceTestCase.Id))]
	public ServiceTestCase ServiceTestCase { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuiteExecutionAuditTestCaseLinks_ServiceTestSuiteExecutionAudits_ServiceTestSuiteExecutionAuditId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestSuiteExecutionAuditId), OtherKey = nameof(TestManagement.ServiceTestSuiteExecutionAudit.Id))]
	public ServiceTestSuiteExecutionAudit ServiceTestSuiteExecutionAudit { get; set; } = null!;
	#endregion
}
