// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceRequestFileHistorys")]
public partial class ServiceRequestFileHistory
{
	/// <summary>
	/// Unique identifier for this ServiceRequestFileHistorys record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Format of the stored file payload, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)

	/// <summary>
	/// Original name of the stored file.
	/// </summary>
	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Binary content of the stored file.
	/// </summary>
	[Column("FileData", CanBeNull = false)]
	public byte[] FileData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the file content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// SHA-256 hash of the stored file content.
	/// </summary>
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFileHistorys backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFileEmbedding.ServiceRequestFileHistoryId))]
	public IEnumerable<ServiceRequestFileEmbedding> ServiceRequestFileEmbeddings { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFileHistorys_ServiceRequestFiles_ServiceRequestFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(TestManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile ServiceRequestFile { get; set; } = null!;
	#endregion
}
