// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

/// <summary>
/// Links service test suite execution audits to individual test case executions.
/// Captures detailed HTTP execution information for each test case within a suite run.
/// </summary>
[Table("ServiceTestSuiteTestCaseLinkAudits")]
public partial class ServiceTestSuiteTestCaseLinkAudit
{
	/// <summary>
	/// Unique identifier for this ServiceTestSuiteTestCaseLinkAudits record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related ServiceTestSuiteTestCaseLinks record.
	/// </summary>
	[Column("ServiceTestSuiteTestCaseLinkId")]
	public int ServiceTestSuiteTestCaseLinkId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId")]
	public long ServiceResponseFileId { get; set; } // bigint

	/// <summary>
	/// Execution order within the audit run.
	/// </summary>
	[Column("ExecutionOrder")]
	public int ExecutionOrder { get; set; } // int

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Final execution status (Pending, InProgress, Completed, Failed).
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details about the execution, including error messages if applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the user who executed this test case.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestSuiteTestCaseLinkAudits_ServiceTestSuiteTestCaseLinks_ServiceTestSuiteTestCaseLinkId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestSuiteTestCaseLinkId), OtherKey = nameof(TestManagement.ServiceTestSuiteTestCaseLink.Id))]
	public ServiceTestSuiteTestCaseLink ServiceTestSuiteTestCaseLink { get; set; } = null!;
	#endregion
}

