// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceAppAuthentications")]
public partial class ServiceAppAuthentication
{
	/// <summary>
	/// Unique identifier for this ServiceAppAuthentications record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Authentication mechanism used to access a service application.
	/// </summary>
	[Column("AuthenticationType", CanBeNull = false)]
	public string AuthenticationType { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Algorithm used to encrypt stored credentials.
	/// </summary>
	[Column("EncryptionAlgorithmType")]
	public string? EncryptionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// Encrypted JSON document containing authentication credentials.
	/// </summary>
	[Column("EncryptedCredentialsJson", CanBeNull = false)]
	public string EncryptedCredentialsJson { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceApplications_ServiceAppAuthentications_AuthenticationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceApplication.ServiceAppAuthenticationId))]
	public IEnumerable<ServiceApplication> ServiceApplications { get; set; } = null!;
	#endregion
}
