// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceApplications")]
public partial class ServiceApplication
{
	/// <summary>
	/// Unique identifier for this ServiceApplications record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Service protocol category, such as SOAP or REST.
	/// </summary>
	[Column("ServiceType", CanBeNull = false)]
	public string ServiceType { get; set; } = null!; // varchar(10)

	/// <summary>
	/// Identifier of the related ServiceAppAuthentications record.
	/// </summary>
	[Column("ServiceAppAuthenticationId")]
	public long? ServiceAppAuthenticationId { get; set; } // bigint

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)

	/// <summary>
	/// Base HTTP or HTTPS URL for the service application.
	/// </summary>
	[Column("BaseUrl", CanBeNull = false)]
	public string BaseUrl { get; set; } = null!; // nvarchar(500)

	/// <summary>
	/// Type of service definition, such as WSDL, Swagger, or OpenAPI.
	/// </summary>
	[Column("DefinitionType")]
	public string? DefinitionType { get; set; } // varchar(20)

	/// <summary>
	/// Path to the service definition relative to the application base URL.
	/// </summary>
	[Column("DefinitionRelativeUrl")]
	public string? DefinitionRelativeUrl { get; set; } // nvarchar(250)

	/// <summary>
	/// Path to the health-check endpoint relative to the application base URL.
	/// </summary>
	[Column("HealthcheckRelativeUrl")]
	public string? HealthcheckRelativeUrl { get; set; } // nvarchar(250)

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(max)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceApplications_ServiceAppAuthentications_ServiceAppAuthenticationId
	/// </summary>
	[Association(ThisKey = nameof(ServiceAppAuthenticationId), OtherKey = nameof(TestManagement.ServiceAppAuthentication.Id))]
	public ServiceAppAuthentication? ServiceAppAuthentication { get; set; }

	/// <summary>
	/// FK_ServiceDefinitionSyncs_ServiceApplications_ServiceApplicationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceDefinitionSync.ServiceApplicationId))]
	public IEnumerable<ServiceDefinitionSync> ServiceDefinitionSyncs { get; set; } = null!;

	/// <summary>
	/// FK_ServiceOperations_ServiceApplications_ServiceApplicationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceOperation.ServiceApplicationId))]
	public IEnumerable<ServiceOperation> ServiceOperations { get; set; } = null!;
	#endregion
}
