// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceRequestFileEmbeddings")]
public partial class ServiceRequestFileEmbedding
{
	/// <summary>
	/// Unique identifier for this ServiceRequestFileEmbeddings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related BinaryEmbeddingsStore record.
	/// </summary>
	[Column("BinaryEmbeddingsStoreId")]
	public int BinaryEmbeddingsStoreId { get; set; } // int

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// SHA-256 hash of the stored file content.
	/// </summary>
	[Column("FileHash", CanBeNull = false)]
	public string FileHash { get; set; } = null!; // varchar(64)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFiles
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(TestManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile ServiceRequestFile { get; set; } = null!;
	#endregion
}
