// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceRequestFileEmbeddings")]
public partial class ServiceRequestFileEmbedding
{
	/// <summary>
	/// Unique identifier for this ServiceRequestFileEmbeddings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int? ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceRequestFileHistorys record.
	/// </summary>
	[Column("ServiceRequestFileHistoryId")]
	public int? ServiceRequestFileHistoryId { get; set; } // int

	/// <summary>
	/// Format of the stored file payload, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)

	/// <summary>
	/// Original name of the stored file.
	/// </summary>
	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Binary content of the stored file.
	/// </summary>
	[Column("FileData", CanBeNull = false)]
	public byte[] FileData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the file content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// SHA-256 hash of the stored file content.
	/// </summary>
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFileHistorys
	/// </summary>
	[Association(ThisKey = nameof(ServiceRequestFileHistoryId), OtherKey = nameof(TestManagement.ServiceRequestFileHistory.Id))]
	public ServiceRequestFileHistory? ServiceRequestFileHistory { get; set; }

	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFiles
	/// </summary>
	[Association(ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(TestManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile? ServiceRequestFile { get; set; }
	#endregion
}
