// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceRequestFiles")]
public partial class ServiceRequestFile
{
	/// <summary>
	/// Unique identifier for this ServiceRequestFiles record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceOperations record.
	/// </summary>
	[Column("ServiceOperationId")]
	public int ServiceOperationId { get; set; } // int

	/// <summary>
	/// Format of the stored file payload, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Indicates whether this record is a complete base snapshot (1) or a differential delta (0).
	/// </summary>
	[Column("IsBaseSnapshot")]
	public bool IsBaseSnapshot { get; set; } // bit

	/// <summary>
	/// Identifier of the base snapshot record in the delta chain.
	/// </summary>
	[Column("ParentBaseId")]
	public int? ParentBaseId { get; set; } // int

	/// <summary>
	/// Identifier of the immediate predecessor record in the delta chain.
	/// </summary>
	[Column("ParentDeltaId")]
	public int? ParentDeltaId { get; set; } // int

	/// <summary>
	/// Depth of this record in the delta chain (0 for base snapshots).
	/// </summary>
	[Column("DeltaDepth")]
	public int DeltaDepth { get; set; } // int

	/// <summary>
	/// Compressed binary content stored for this record.
	/// </summary>
	[Column("CompressedData", CanBeNull = false)]
	public byte[] CompressedData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the file content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// SHA-256 hash of the stored content for integrity verification.
	/// </summary>
	[Column("ContentHash")]
	public string? ContentHash { get; set; } // varchar(64)

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionAuditResponseFileLinks_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionAuditResponseFileLink.ServiceRequestFileId))]
	public IEnumerable<DirectExecutionAuditResponseFileLink> DirectExecutionAuditResponseFileLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFiles backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFileEmbedding.ServiceRequestFileId))]
	public IEnumerable<ServiceRequestFileEmbedding> ServiceRequestFileEmbeddings { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFiles_ServiceOperations_ServiceOperationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceOperationId), OtherKey = nameof(TestManagement.ServiceOperation.Id))]
	public ServiceOperation ServiceOperation { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFiles_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFile.ServiceRequestFileId))]
	public IEnumerable<ServiceResponseFile> ServiceResponseFiles { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestCases_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestCase.ServiceRequestFileId))]
	public IEnumerable<ServiceTestCase> ServiceTestCases { get; set; } = null!;
	#endregion
}
