// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceTestCaseRuleSetLinks")]
public partial class ServiceTestCaseRuleSetLink
{
	/// <summary>
	/// Unique identifier for this ServiceTestCaseRuleSetLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceTestCases record.
	/// </summary>
	[Column("ServiceTestCaseId")]
	public int ServiceTestCaseId { get; set; } // int

	/// <summary>
	/// Identifier of the related RuleSets record.
	/// </summary>
	[Column("RuleSetId")]
	public int RuleSetId { get; set; } // int

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestCaseRuleSetLinks_ServiceTestCases_ServiceTestCaseId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestCaseId), OtherKey = nameof(TestManagement.ServiceTestCase.Id))]
	public ServiceTestCase ServiceTestCase { get; set; } = null!;
	#endregion
}
