// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceTestSuiteTestCaseLinks")]
public partial class ServiceTestSuiteTestCaseLink
{
	/// <summary>
	/// Unique identifier for this ServiceTestSuiteTestCaseLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related ServiceTestSuites record.
	/// </summary>
	[Column("ServiceTestSuiteId")]
	public int ServiceTestSuiteId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceTestCases record.
	/// </summary>
	[Column("ServiceTestCaseId")]
	public int ServiceTestCaseId { get; set; } // int

	/// <summary>
	/// Ordinal position that determines the sequence in which this item is executed within its parent group or suite.
	/// </summary>
	[Column("ExecutionOrder")]
	public int ExecutionOrder { get; set; } // int

	/// <summary>
	/// Indicates whether this record is active and available for use (1) or soft-deleted (0).
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestSuiteTestCaseLinkAudits_ServiceTestSuiteTestCaseLinks_ServiceTestSuiteTestCaseLinkId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestSuiteTestCaseLinkAudit.ServiceTestSuiteTestCaseLinkId))]
	public IEnumerable<ServiceTestSuiteTestCaseLinkAudit> ServiceTestSuiteTestCaseLinkAudits { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuiteTestCaseLinks_ServiceTestCases_ServiceTestCaseId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestCaseId), OtherKey = nameof(TestManagement.ServiceTestCase.Id))]
	public ServiceTestCase ServiceTestCase { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuiteTestCaseLinks_ServiceTestSuites_ServiceTestSuiteId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestSuiteId), OtherKey = nameof(TestManagement.ServiceTestSuite.Id))]
	public ServiceTestSuite ServiceTestSuite { get; set; } = null!;
	#endregion
}
