// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceResponseFileEmbeddings")]
public partial class ServiceResponseFileEmbedding
{
	/// <summary>
	/// Unique identifier for this ServiceResponseFileEmbeddings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId")]
	public int ServiceResponseFileId { get; set; } // int

	/// <summary>
	/// Value of the BinaryEmbeddingsStoreId field for this ServiceResponseFileEmbeddings record.
	/// </summary>
	[Column("BinaryEmbeddingsStoreId")]
	public int BinaryEmbeddingsStoreId { get; set; } // int

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// SHA-256 hash of the stored file content.
	/// </summary>
	[Column("FileHash", CanBeNull = false)]
	public string FileHash { get; set; } = null!; // varchar(64)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceResponseFileEmbeddings_ServiceResponseFiles_ServiceResponseFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceResponseFileId), OtherKey = nameof(TestManagement.ServiceResponseFile.Id))]
	public ServiceResponseFile ServiceResponseFile { get; set; } = null!;
	#endregion
}
