// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

[Table("ServiceTestExecutionAudits")]
public partial class ServiceTestExecutionAudit
{
	/// <summary>
	/// Unique identifier for this ServiceTestExecutionAudits record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceTestSuites record.
	/// </summary>
	[Column("ServiceTestSuiteId")]
	public int ServiceTestSuiteId { get; set; } // int

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime

	/// <summary>
	/// Final status of the execution.
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details captured during execution, including errors when applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestExecutionAuditTestSuitLinks_ServiceTestExecutionAudits_ServiceTestExecutionAuditId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestExecutionAuditTestSuitLink.ServiceTestExecutionAuditId))]
	public IEnumerable<ServiceTestExecutionAuditTestSuitLink> ServiceTestExecutionAuditTestSuitLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestExecutionAudits_ServiceTestSuites_ServiceTestSuiteId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestSuiteId), OtherKey = nameof(TestManagement.ServiceTestSuite.Id))]
	public ServiceTestSuite ServiceTestSuite { get; set; } = null!;
	#endregion
}
