// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.TestManagement;

public partial class TestDbContext : DataConnection
{
	public TestDbContext()
	{
		InitDataContext();
	}

	public TestDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public TestDbContext(DataOptions<TestDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<DirectExecutionAudit>                       DirectExecutionAudits                       => this.GetTable<DirectExecutionAudit>();

	public ITable<DirectExecutionAuditResponseFileLink>       DirectExecutionAuditResponseFileLinks       => this.GetTable<DirectExecutionAuditResponseFileLink>();

	public ITable<ServiceAppAuthentication>                   ServiceAppAuthentications                   => this.GetTable<ServiceAppAuthentication>();

	public ITable<ServiceApplication>                         ServiceApplications                         => this.GetTable<ServiceApplication>();

	public ITable<ServiceDefinitionSync>                      ServiceDefinitionSyncs                      => this.GetTable<ServiceDefinitionSync>();

	public ITable<ServiceOperationSchema>                     ServiceOperationSchemas                     => this.GetTable<ServiceOperationSchema>();

	public ITable<ServiceOperation>                           ServiceOperations                           => this.GetTable<ServiceOperation>();

	public ITable<ServiceRequestFileEmbedding>                ServiceRequestFileEmbeddings                => this.GetTable<ServiceRequestFileEmbedding>();

	public ITable<ServiceRequestFile>                         ServiceRequestFiles                         => this.GetTable<ServiceRequestFile>();

	public ITable<ServiceResponseFileEmbedding>               ServiceResponseFileEmbeddings               => this.GetTable<ServiceResponseFileEmbedding>();

	public ITable<ServiceResponseFile>                        ServiceResponseFiles                        => this.GetTable<ServiceResponseFile>();

	public ITable<ServiceTestCaseRuleSetLink>                 ServiceTestCaseRuleSetLinks                 => this.GetTable<ServiceTestCaseRuleSetLink>();

	public ITable<ServiceTestCase>                            ServiceTestCases                            => this.GetTable<ServiceTestCase>();

	public ITable<ServiceTestSuiteExecutionAuditTestCaseLink> ServiceTestSuiteExecutionAuditTestCaseLinks => this.GetTable<ServiceTestSuiteExecutionAuditTestCaseLink>();

	public ITable<ServiceTestSuiteExecutionAudit>             ServiceTestSuiteExecutionAudits             => this.GetTable<ServiceTestSuiteExecutionAudit>();

	public ITable<ServiceTestSuiteTestCaseLink>               ServiceTestSuiteTestCaseLinks               => this.GetTable<ServiceTestSuiteTestCaseLink>();

	public ITable<ServiceTestSuite>                           ServiceTestSuites                           => this.GetTable<ServiceTestSuite>();

	public ITable<SoapNamespace>                              SoapNamespaces                              => this.GetTable<SoapNamespace>();
}

public static partial class ExtensionMethods
{
	#region Table Extensions
	public static DirectExecutionAudit? Find(this ITable<DirectExecutionAudit> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionAudit?> FindAsync(this ITable<DirectExecutionAudit> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static DirectExecutionAuditResponseFileLink? Find(this ITable<DirectExecutionAuditResponseFileLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionAuditResponseFileLink?> FindAsync(this ITable<DirectExecutionAuditResponseFileLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceAppAuthentication? Find(this ITable<ServiceAppAuthentication> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceAppAuthentication?> FindAsync(this ITable<ServiceAppAuthentication> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceApplication? Find(this ITable<ServiceApplication> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceApplication?> FindAsync(this ITable<ServiceApplication> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceDefinitionSync? Find(this ITable<ServiceDefinitionSync> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceDefinitionSync?> FindAsync(this ITable<ServiceDefinitionSync> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceOperationSchema? Find(this ITable<ServiceOperationSchema> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceOperationSchema?> FindAsync(this ITable<ServiceOperationSchema> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceOperation? Find(this ITable<ServiceOperation> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceOperation?> FindAsync(this ITable<ServiceOperation> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceRequestFileEmbedding? Find(this ITable<ServiceRequestFileEmbedding> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceRequestFileEmbedding?> FindAsync(this ITable<ServiceRequestFileEmbedding> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceRequestFile? Find(this ITable<ServiceRequestFile> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceRequestFile?> FindAsync(this ITable<ServiceRequestFile> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFileEmbedding? Find(this ITable<ServiceResponseFileEmbedding> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFileEmbedding?> FindAsync(this ITable<ServiceResponseFileEmbedding> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFile? Find(this ITable<ServiceResponseFile> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFile?> FindAsync(this ITable<ServiceResponseFile> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestCaseRuleSetLink? Find(this ITable<ServiceTestCaseRuleSetLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestCaseRuleSetLink?> FindAsync(this ITable<ServiceTestCaseRuleSetLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestCase? Find(this ITable<ServiceTestCase> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestCase?> FindAsync(this ITable<ServiceTestCase> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestSuiteExecutionAuditTestCaseLink? Find(this ITable<ServiceTestSuiteExecutionAuditTestCaseLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestSuiteExecutionAuditTestCaseLink?> FindAsync(this ITable<ServiceTestSuiteExecutionAuditTestCaseLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestSuiteExecutionAudit? Find(this ITable<ServiceTestSuiteExecutionAudit> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestSuiteExecutionAudit?> FindAsync(this ITable<ServiceTestSuiteExecutionAudit> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestSuiteTestCaseLink? Find(this ITable<ServiceTestSuiteTestCaseLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestSuiteTestCaseLink?> FindAsync(this ITable<ServiceTestSuiteTestCaseLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceTestSuite? Find(this ITable<ServiceTestSuite> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceTestSuite?> FindAsync(this ITable<ServiceTestSuite> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static SoapNamespace? Find(this ITable<SoapNamespace> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<SoapNamespace?> FindAsync(this ITable<SoapNamespace> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}
	#endregion
}
