// <auto-generated>
// Generated from v_RuleSetContextLinks
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.RuleManagement.Views;
using OrbitHub.Data.RuleManagement;

namespace OrbitHub.Data.Repositories.RuleManagement.Views;

public class RuleSetContextLinkViewRepository
{
    private readonly RuleDbContext _ctx;

    public RuleSetContextLinkViewRepository(RuleDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<RuleSetContextLinkView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<RuleSetContextLinkView>(
                "SELECT * FROM [dbo].[v_RuleSetContextLinks]"
            )).ToList();
            return RepositoryResult<List<RuleSetContextLinkView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<RuleSetContextLinkView>>.Fail(ex.Message);
        }
    }
}
