// <auto-generated>
// Generated from CreateRuleSet
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Models;

public class CreateRuleSetInput
{
    public string WorkflowName { get; set; } = default!;
    public string RuleContent { get; set; } = default!;
    public int OutputTypeId { get; set; } = default!;
    public string? Description { get; set; } = default!;
    public bool? IsActive { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}