// <auto-generated>
// Generated from LogRuleExecution
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.RuleManagement.Models;

public class LogRuleExecutionInput
{
    public int RuleSetId { get; set; } = default!;
    public byte[]? InputCompressedContent { get; set; } = default!;
    public int? InputUncompressedSizeBytes { get; set; } = default!;
    public string? InputContentHash { get; set; } = default!;
    public byte[]? OutputCompressedContent { get; set; } = default!;
    public int? OutputUncompressedSizeBytes { get; set; } = default!;
    public string? OutputContentHash { get; set; } = default!;
    public string? CompressionAlgorithmType { get; set; } = default!;
    public bool IsSuccess { get; set; } = default!;
    public string? ErrorMessage { get; set; } = default!;
    public int? ExecutionTimeMs { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}