// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record CompleteDirectExecutionAuditInput
{
    public required int AuditId { get; init; }
    public required string ExecutionStatus { get; init; }
    public string? ExecutionDetails { get; init; }
}