// <auto-generated>
// Generated from CreateServiceTestCase
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class CreateServiceTestCaseOutput
{
    public int? TestCaseId { get; set; }
    public string? Name { get; set; }
    public int? ServiceRequestFileId { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}