// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public sealed record CreateDirectExecutionAuditInput
{
    public required string Name { get; init; }
    public string? ExecutedBy { get; init; }
}