// <auto-generated>
// Generated from CreateServiceOperation
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class CreateServiceOperationOutput
{
    public int? OperationId { get; set; }
    public int? ServiceApplicationId { get; set; }
    public string? OperationName { get; set; }
    public string? EndpointOrAction { get; set; }
    public string? HttpMethod { get; set; }
    public string? Description { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}