// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetDirectExecutionAuditResponseFileLinksByAuditIdInput
{
    public required int DirectExecutionAuditId { get; init; }
}