// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public sealed record GetDirectExecutionAuditResponseFileLinksByAuditIdOutput
{
    public required int Id { get; init; }
    public required int DirectExecutionAuditId { get; init; }
    public required int ServiceRequestFileId { get; init; }
    public required int ExecutionOrder { get; init; }
    public required string ExecutionStatus { get; init; }
    public int? HttpStatusCode { get; init; }
    public int? HttpRequestDurationMs { get; init; }
    public string? HttpContentType { get; init; }
    public string? HttpRequestHeaders { get; init; }
    public string? HttpResponseHeaders { get; init; }
    public required DateTime ExecutedAt { get; init; }
    public DateTime? ExecutionCompletedAt { get; init; }
}