// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetDirectExecutionAuditByIdInput
{
    public required int AuditId { get; init; }
}