// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public sealed record GetDirectExecutionAuditByIdInput
{
    public required int AuditId { get; init; }
}