// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public sealed record GetServiceDefinitionSyncLatestVersionOutput
{
    public string? RecordVersion { get; init; }
}