// <auto-generated>
// Generated from GetServiceApplicationHistory
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceApplicationHistoryOutput
{
    public int? VersionId { get; set; }
    public Guid? PublicId { get; set; }
    public int? VersionNumber { get; set; }
    public int? TotalVersions { get; set; }
    public bool? IsLatestVersion { get; set; }
    public string? ServiceName { get; set; }
    public string? ServiceType { get; set; }
    public string? BaseUrl { get; set; }
    public string? DefinitionType { get; set; }
    public string? DefinitionRelativeUrl { get; set; }
    public string? HealthcheckRelativeUrl { get; set; }
    public string? Description { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public string? PreviousVersion { get; set; }
    public int? PreviousVersionId { get; set; }
    public string? NextVersion { get; set; }
    public int? NextVersionId { get; set; }
    public int? DaysSincePreviousVersion { get; set; }
    public int? HoursSincePreviousVersion { get; set; }
    public bool? UrlChanged { get; set; }
    public string? ChangeType { get; set; }
    public string? AuthDetails { get; set; }
    public string? ServiceUsage { get; set; }
}