// <auto-generated>
// Generated from GetServiceOperationSchemas
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceOperationSchemasInput
{
    public Guid ServiceApplicationPublicId { get; set; } = default!;
    public string? OperationName { get; set; } = default!;
    public bool? IncludeContent { get; set; } = default!;
}