// <auto-generated>
// Generated from GetServiceDefinitionSync
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceDefinitionSyncOutput
{
    public int? SyncId { get; set; }
    public int? ServiceApplicationId { get; set; }
    public string? DefinitionUrl { get; set; }
    public byte[]? CompressedContent { get; set; }
    public int? UncompressedSizeBytes { get; set; }
    public string? CompressionAlgorithmType { get; set; }
    public string? ContentHash { get; set; }
    public string? SyncRecordVersion { get; set; }
    public DateTime? SyncCreatedAt { get; set; }
    public string? SyncCreatedBy { get; set; }
    public DateTime? SyncLastUpdatedAt { get; set; }
    public string? SyncLastUpdatedBy { get; set; }
    public Guid? ServicePublicId { get; set; }
    public string? ServiceName { get; set; }
    public string? ServiceType { get; set; }
    public string? BaseUrl { get; set; }
    public string? DefinitionType { get; set; }
    public string? DefinitionRelativeUrl { get; set; }
    public string? HealthcheckRelativeUrl { get; set; }
    public bool? ServiceIsActive { get; set; }
}