// <auto-generated>
// Generated from GetServiceResponseFilesByRequest
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public class GetServiceResponseFilesByRequestInput
{
    public int RequestFileId { get; set; } = default!;
    public bool? IncludeInactive { get; set; } = default!;
}