// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceRequestFileConsecutiveDeltaCountInput
{
    public required int RequestFileId { get; init; }
}