// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceDefinitionSyncLatestVersionInput
{
    public required int ServiceApplicationId { get; init; }
}