// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceOperationByIdOutput
{
    public required int Id { get; init; }
    public required int ServiceApplicationId { get; init; }
    public required string OperationName { get; init; }
    public string? EndpointOrAction { get; init; }
    public string? HttpMethod { get; init; }
    public string? Description { get; init; }
    public required bool IsActive { get; init; }
    public required string RecordVersion { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required string CreatedBy { get; init; }
    public DateTime? LastUpdatedAt { get; init; }
    public string? LastUpdatedBy { get; init; }
}