// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceRequestFileByOperationAndNameInput
{
    public required int ServiceOperationId { get; init; }
    public required string Name { get; init; }
}