// <auto-generated>
// Generated from GetServiceResponseFileChain
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceResponseFileChainInput
{
    public int ResponseFileId { get; set; } = default!;
    public bool? IncludeData { get; set; } = default!;
}