// <auto-generated> This file has been auto generated. </auto-generated>

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceApplicationByIdOutput
{
    public required int Id { get; init; }
    public required Guid PublicId { get; init; }
    public required string ServiceType { get; init; }
    public long? ServiceAppAuthenticationId { get; init; }
    public required string Name { get; init; }
    public required string BaseUrl { get; init; }
    public string? DefinitionType { get; init; }
    public string? DefinitionRelativeUrl { get; init; }
    public string? HealthcheckRelativeUrl { get; init; }
    public string? Description { get; init; }
    public required bool IsActive { get; init; }
    public required int RecordVersion { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required string CreatedBy { get; init; }
    public DateTime? LastUpdatedAt { get; init; }
    public string? LastUpdatedBy { get; init; }
}