// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public sealed record GetServiceRequestFileConsecutiveDeltaCountOutput
{
    public required int DeltaCount { get; init; }
}