// <auto-generated>
// Generated from GetServiceRequestFilesByOperation
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceRequestFilesByOperationInput
{
    public int OperationId { get; set; } = default!;
    public bool? IncludeInactive { get; set; } = default!;
    public string? FileType { get; set; } = default!;
    public string? NameFilter { get; set; } = default!;
}