// <auto-generated>
// Generated from LinkRuleSetToTestCase
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public class LinkRuleSetToTestCaseInput
{
    public int ServiceTestCaseId { get; set; } = default!;
    public int RuleSetId { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}