// <auto-generated>
// Generated from LinkRuleSetToTestCase
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class LinkRuleSetToTestCaseOutput
{
    public int? LinkId { get; set; }
    public string? Message { get; set; }
    public long? AuditActivityId { get; set; }
}