// <auto-generated>
// Generated from LogTestCaseExecution
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public class LogTestCaseExecutionOutput
{
    public int? ExecutionLinkId { get; set; }
    public long? AuditActivityId { get; set; }
}