// <auto-generated>
// Generated from ToggleServiceApplicationActive
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.TestManagement.Models;

public class ToggleServiceApplicationActiveInput
{
    public Guid PublicId { get; set; } = default!;
    public string UserId { get; set; } = default!;
    public bool IsActive { get; set; } = default!;
}