// <auto-generated>
// Generated from UnlinkRuleSetFromTestCase
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UnlinkRuleSetFromTestCaseInput
{
    public int LinkId { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}