// <auto-generated>
// Generated from UpdateTestCaseExecution
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpdateTestCaseExecutionInput
{
    public int ExecutionLinkId { get; set; } = default!;
    public int? HttpStatusCode { get; set; } = default!;
    public int? HttpRequestDurationMs { get; set; } = default!;
    public string? HttpResponseHeaders { get; set; } = default!;
    public string? HttpContentType { get; set; } = default!;
    public long? HttpContentLength { get; set; } = default!;
    public string? ExecutionStatus { get; set; } = default!;
    public string? ExecutionDetails { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}