// <auto-generated>
// Generated from UpdateServiceRequestFile
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpdateServiceRequestFileOutput
{
    public int? FileId { get; set; }
    public string? Name { get; set; }
    public string? FileFormat { get; set; }
    public byte[]? CompressedData { get; set; }
    public int? UncompressedSizeBytes { get; set; }
    public string? CompressionAlgorithmType { get; set; }
    public string? ContentHash { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}