// <auto-generated>
// Generated from v_ActiveSoapNamespaces
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ActiveSoapNamespaceViewRepository
{
    private readonly TestDbContext _ctx;

    public ActiveSoapNamespaceViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ActiveSoapNamespaceView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ActiveSoapNamespaceView>(
                "SELECT * FROM [dbo].[v_ActiveSoapNamespaces]"
            )).ToList();
            return RepositoryResult<List<ActiveSoapNamespaceView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ActiveSoapNamespaceView>>.Fail(ex.Message);
        }
    }
}
