// <auto-generated>
// Generated from v_ServiceTestCaseExecutionHistory
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceTestCaseExecutionHistoryView
{
    public long ExecutionLinkId { get; set; }
    public long ServiceTestSuiteExecutionAuditId { get; set; }
    public long ServiceTestCaseId { get; set; }
    public long? ServiceResponseFileId { get; set; }
    public DateTime ExecutedAt { get; set; }
    public DateTime? ExecutionCompletedAt { get; set; }
    public int? HttpStatusCode { get; set; }
    public string? HttpVersion { get; set; }
    public long? HttpRequestDurationMs { get; set; }
    public string? HttpContentType { get; set; }
    public long? HttpContentLength { get; set; }
    public string? TestExecutionStatus { get; set; }
    public string? TestExecutionDetails { get; set; }
    public string? TestExecutedBy { get; set; }
    public string TestCaseName { get; set; } = string.Empty;
    public bool? TestCaseIsActive { get; set; }
    public string? ResponseFileName { get; set; }
    public string? ResponseFileFormat { get; set; }
    public long SuiteId { get; set; }
    public string SuiteName { get; set; } = string.Empty;
    public string? SuiteExecutionStatus { get; set; }
    public DateTime? SuiteExecutedAt { get; set; }
    public string ExecutedByFullName { get; set; } = string.Empty;
    public string StatusDisplay { get; set; } = string.Empty;
    public decimal? ResponseTimeSeconds { get; set; }
}
