// <auto-generated>
// Generated from v_ServiceResponseFilesWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceResponseFileWithDetailsViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceResponseFileWithDetailsViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceResponseFileWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceResponseFileWithDetailsView>(
                "SELECT * FROM [dbo].[v_ServiceResponseFilesWithDetails]"
            )).ToList();
            return RepositoryResult<List<ServiceResponseFileWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceResponseFileWithDetailsView>>.Fail(ex.Message);
        }
    }
}
