// <auto-generated>
// Generated from v_ServiceTestCaseExecutionHistory
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceTestCaseExecutionHistoryViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceTestCaseExecutionHistoryViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceTestCaseExecutionHistoryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceTestCaseExecutionHistoryView>(
                "SELECT * FROM [dbo].[v_ServiceTestCaseExecutionHistory]"
            )).ToList();
            return RepositoryResult<List<ServiceTestCaseExecutionHistoryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceTestCaseExecutionHistoryView>>.Fail(ex.Message);
        }
    }
}
