// <auto-generated>
// Generated from v_ServiceRequestFileDeltaSummary
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceRequestFileDeltaSummaryView
{
    public long BaseFileId { get; set; }
    public string BaseFileName { get; set; } = string.Empty;
    public string? FileFormat { get; set; }
    public long? BaseSize { get; set; }
    public DateTime BaseCreatedAt { get; set; }
    public string? BaseHash { get; set; }
    public int TotalDeltas { get; set; }
    public int MaxDepth { get; set; }
    public DateTime? FirstDeltaCreated { get; set; }
    public DateTime? LastDeltaCreated { get; set; }
    public long? TotalDeltaSize { get; set; }
    public int UniqueDeltaNames { get; set; }
    public long? TotalSize { get; set; }
    public long? StorageSavingsBytes { get; set; }
    public decimal? StorageSavingsPercent { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
}
