// <auto-generated>
// Generated from v_ServiceOperationsSummary
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceOperationsSummaryViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceOperationsSummaryViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceOperationsSummaryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceOperationsSummaryView>(
                "SELECT * FROM [dbo].[v_ServiceOperationsSummary]"
            )).ToList();
            return RepositoryResult<List<ServiceOperationsSummaryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceOperationsSummaryView>>.Fail(ex.Message);
        }
    }
}
