// <auto-generated>
// Generated from v_ServiceResponseFileEmbeddingsWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceResponseFileEmbeddingWithDetailsView
{
    public long EmbeddingId { get; set; }
    public long ServiceResponseFileId { get; set; }
    public long? BinaryEmbeddingsStoreId { get; set; }
    public string? EmbeddingName { get; set; }
    public string? EmbeddingFileHash { get; set; }
    public DateTime? EmbeddingCreatedAt { get; set; }
    public string? EmbeddingCreatedBy { get; set; }
    public DateTime? EmbeddingLastUpdatedAt { get; set; }
    public string? EmbeddingLastUpdatedBy { get; set; }
    public long ResponseFileId { get; set; }
    public string ResponseFileName { get; set; } = string.Empty;
    public string? ResponseFileFormat { get; set; }
    public bool? ResponseIsBase { get; set; }
    public int? ResponseDeltaDepth { get; set; }
    public long? ResponseSize { get; set; }
    public string? ResponseFileHash { get; set; }
    public bool? ResponseIsActive { get; set; }
    public long RequestFileId { get; set; }
    public string RequestFileName { get; set; } = string.Empty;
    public string? RequestFileFormat { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public string? HttpMethod { get; set; }
    public string? EndpointOrAction { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public string? BinaryFileHash { get; set; }
    public string? BinaryCompression { get; set; }
    public string OverallStatus { get; set; } = string.Empty;
    public string FullPath { get; set; } = string.Empty;
}
