// <auto-generated>
// Generated from v_ServiceRequestFileEmbeddingsWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceRequestFileEmbeddingWithDetailsViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceRequestFileEmbeddingWithDetailsViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceRequestFileEmbeddingWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceRequestFileEmbeddingWithDetailsView>(
                "SELECT * FROM [dbo].[v_ServiceRequestFileEmbeddingsWithDetails]"
            )).ToList();
            return RepositoryResult<List<ServiceRequestFileEmbeddingWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceRequestFileEmbeddingWithDetailsView>>.Fail(ex.Message);
        }
    }
}
