// <auto-generated>
// Generated from v_ServiceTestSuitesWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceTestSuiteWithDetailsViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceTestSuiteWithDetailsViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceTestSuiteWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceTestSuiteWithDetailsView>(
                "SELECT * FROM [dbo].[v_ServiceTestSuitesWithDetails]"
            )).ToList();
            return RepositoryResult<List<ServiceTestSuiteWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceTestSuiteWithDetailsView>>.Fail(ex.Message);
        }
    }
}
