// <auto-generated>
// Generated from v_ServiceRequestResponsePairs
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceRequestResponsePairViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceRequestResponsePairViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceRequestResponsePairView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceRequestResponsePairView>(
                "SELECT * FROM [dbo].[v_ServiceRequestResponsePairs]"
            )).ToList();
            return RepositoryResult<List<ServiceRequestResponsePairView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceRequestResponsePairView>>.Fail(ex.Message);
        }
    }
}
