// <auto-generated>
// Generated from v_ServiceOperationsWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceOperationsWithDetailsView
{
    public long OperationId { get; set; }
    public long ServiceApplicationId { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public string? EndpointOrAction { get; set; }
    public string? HttpMethod { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public int? OperationRecordVersion { get; set; }
    public DateTime OperationCreatedAt { get; set; }
    public string OperationCreatedBy { get; set; } = string.Empty;
    public DateTime? OperationLastUpdatedAt { get; set; }
    public string? OperationLastUpdatedBy { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public string? BaseUrl { get; set; }
    public string? DefinitionType { get; set; }
    public string? DefinitionRelativeUrl { get; set; }
    public bool? ServiceIsActive { get; set; }
    public int? ServiceRecordVersion { get; set; }
    public bool HasSchema { get; set; }
    public int SchemaCount { get; set; }
    public string OperationStatus { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public int DaysSinceCreation { get; set; }
    public int DaysSinceLastUpdate { get; set; }
}
