// <auto-generated>
// Generated from v_ServiceRequestFileDeltaSummary
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceRequestFileDeltaSummaryViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceRequestFileDeltaSummaryViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceRequestFileDeltaSummaryView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceRequestFileDeltaSummaryView>(
                "SELECT * FROM [dbo].[v_ServiceRequestFileDeltaSummary]"
            )).ToList();
            return RepositoryResult<List<ServiceRequestFileDeltaSummaryView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceRequestFileDeltaSummaryView>>.Fail(ex.Message);
        }
    }
}
