// <auto-generated>
// Generated from v_ServiceOperationsWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceOperationsWithDetailsViewRepository
{
    private readonly TestDbContext _ctx;

    public ServiceOperationsWithDetailsViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<ServiceOperationsWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<ServiceOperationsWithDetailsView>(
                "SELECT * FROM [dbo].[v_ServiceOperationsWithDetails]"
            )).ToList();
            return RepositoryResult<List<ServiceOperationsWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<ServiceOperationsWithDetailsView>>.Fail(ex.Message);
        }
    }
}
