// <auto-generated>
// Generated from v_SoapNamespacesWithDetails
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.TestManagement.Views;
using OrbitHub.Data.TestManagement;

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class SoapNamespacesWithDetailsViewRepository
{
    private readonly TestDbContext _ctx;

    public SoapNamespacesWithDetailsViewRepository(TestDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<SoapNamespacesWithDetailsView>>> GetAllAsync(CancellationToken ct = default)
    {
        try
        {
            var result = (await _ctx.QueryAsync<SoapNamespacesWithDetailsView>(
                "SELECT * FROM [dbo].[v_SoapNamespacesWithDetails]"
            )).ToList();
            return RepositoryResult<List<SoapNamespacesWithDetailsView>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<SoapNamespacesWithDetailsView>>.Fail(ex.Message);
        }
    }
}
