// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

/// <summary>
/// Stores links between direct execution groups and service request files.
/// </summary>
[Table("DirectExecutionGroupServiceRequestFileLinks")]
public partial class DirectExecutionGroupServiceRequestFileLink
{
	/// <summary>
	/// Unique identifier for this DirectExecutionGroupServiceRequestFileLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related DirectExecutionGroups record.
	/// </summary>
	[Column("DirectExecutionGroupId")]
	public int DirectExecutionGroupId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Execution order of this request file within the group.
	/// </summary>
	[Column("ExecutionOrder")]
	public int ExecutionOrder { get; set; } // int

	/// <summary>
	/// Indicates whether this link is active.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the user who created this record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinkAudits_DirectExecutionGroupServiceRequestFileLinkId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionGroupServiceRequestFileLinkAudit.DirectExecutionGroupServiceRequestFileLinkId))]
	public IEnumerable<DirectExecutionGroupServiceRequestFileLinkAudit> DirectExecutionGroupServiceRequestFileLinkAudits { get; set; } = null!;

	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinks_DirectExecutionGroups_DirectExecutionGroupId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(DirectExecutionGroupId), OtherKey = nameof(ServiceAppManagement.DirectExecutionGroup.Id))]
	public DirectExecutionGroup DirectExecutionGroup { get; set; } = null!;

	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinks_ServiceRequestFiles_ServiceRequestFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(ServiceAppManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile ServiceRequestFile { get; set; } = null!;
	#endregion
}

