// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

/// <summary>
/// Stores information about direct execution groups.
/// </summary>
[Table("DirectExecutionGroups")]
public partial class DirectExecutionGroup
{
	/// <summary>
	/// Unique identifier for this DirectExecutionGroups record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Name of the direct execution group.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the user who created this record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionGroupAudits_DirectExecutionGroups backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionGroupAudit.DirectExecutionGroupId))]
	public IEnumerable<DirectExecutionGroupAudit> DirectExecutionGroupAudits { get; set; } = null!;

	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinks_DirectExecutionGroups backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionGroupServiceRequestFileLink.DirectExecutionGroupId))]
	public IEnumerable<DirectExecutionGroupServiceRequestFileLink> DirectExecutionGroupServiceRequestFileLinks { get; set; } = null!;
	#endregion
}

