// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

/// <summary>
/// Stores audit logs for direct execution of group operations.
/// </summary>
[Table("DirectExecutionGroupAudits")]
public partial class DirectExecutionGroupAudit
{
	/// <summary>
	/// Unique identifier for this DirectExecutionGroupAudits record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related DirectExecutionGroups record.
	/// </summary>
	[Column("DirectExecutionGroupId")]
	public int DirectExecutionGroupId { get; set; } // int

	/// <summary>
	/// Snapshot name of the execution group at the time of execution.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Final status of the execution (Pending, InProgress, Completed, Failed).
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details captured during execution, including errors when applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the user who started the execution.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionGroupAudits_DirectExecutionGroups_DirectExecutionGroupId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(DirectExecutionGroupId), OtherKey = nameof(ServiceAppManagement.DirectExecutionGroup.Id))]
	public DirectExecutionGroup DirectExecutionGroup { get; set; } = null!;
	#endregion
}

