// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

/// <summary>
/// Stores detailed HTTP execution audit records for service calls.
/// </summary>
[Table("HttpExecutionDetailAudits")]
public partial class HttpExecutionDetailAudit
{
	/// <summary>
	/// Unique identifier for this HttpExecutionDetailAudits record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Full HTTP request URL including query parameters for GET requests.
	/// </summary>
	[Column("HttpRequestUrl", CanBeNull = false)]
	public string HttpRequestUrl { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// HTTP request method (e.g., 'GET', 'POST', 'PUT', 'DELETE').
	/// </summary>
	[Column("HttpRequestMethod", CanBeNull = false)]
	public string HttpRequestMethod { get; set; } = null!; // nvarchar(10)

	/// <summary>
	/// JSON document containing HTTP request headers.
	/// </summary>
	[Column("HttpRequestHeaders")]
	public string? HttpRequestHeaders { get; set; } // nvarchar(max)

	/// <summary>
	/// HTTP protocol version (e.g., 'HTTP/1.1', 'HTTP/2', 'HTTP/3').
	/// </summary>
	[Column("HttpVersion")]
	public string? HttpVersion { get; set; } // nvarchar(10)

	/// <summary>
	/// HTTP status code returned by the service.
	/// </summary>
	[Column("HttpStatusCode")]
	public int? HttpStatusCode { get; set; } // int

	/// <summary>
	/// Duration of the HTTP request in milliseconds.
	/// </summary>
	[Column("HttpRequestDurationMs")]
	public int? HttpRequestDurationMs { get; set; } // int

	/// <summary>
	/// JSON document containing HTTP response headers.
	/// </summary>
	[Column("HttpResponseHeaders")]
	public string? HttpResponseHeaders { get; set; } // nvarchar(max)

	/// <summary>
	/// Content-Type header returned by the service.
	/// </summary>
	[Column("HttpContentType")]
	public string? HttpContentType { get; set; } // nvarchar(255)

	/// <summary>
	/// Content length of the service response, in bytes.
	/// </summary>
	[Column("HttpContentLength")]
	public long? HttpContentLength { get; set; } // bigint

	/// <summary>
	/// Final status of the execution (Pending, InProgress, Completed, Failed).
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON containing additional execution details.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the user who started the execution.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_HttpExecutionDetailAuditsServiceResponseFilesLinks_HttpExecutionDetailAuditId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(HttpExecutionDetailAuditServiceResponseFileLink.HttpExecutionDetailAuditId))]
	public IEnumerable<HttpExecutionDetailAuditServiceResponseFileLink> HttpExecutionDetailAuditServiceResponseFileLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceAppHealthHttpExecutionDetailAuditLinks_HttpExecutionDetailAuditId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceAppHealthHttpExecutionDetailAuditLink.HttpExecutionDetailAuditId))]
	public IEnumerable<ServiceAppHealthHttpExecutionDetailAuditLink> ServiceAppHealthHttpExecutionDetailAuditLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFileHttpExecutionDetailLinks_HttpExecutionDetailAudits backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFileHttpExecutionDetailLink.HttpExecutionDetailAuditId))]
	public IEnumerable<ServiceResponseFileHttpExecutionDetailLink> ServiceResponseFileHttpExecutionDetailLinks { get; set; } = null!;
	#endregion
}

