// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

[Table("HttpExecutionDetailAuditsServiceResponseFilesLinks")]
public partial class HttpExecutionDetailAuditsServiceResponseFilesLink
{
	/// <summary>
	/// Unique identifier for this HttpExecutionDetailAuditsServiceResponseFilesLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId")]
	public long ServiceResponseFileId { get; set; } // bigint

	/// <summary>
	/// Identifier of the related HttpExecutionDetailAudits record.
	/// </summary>
	[Column("HttpExecutionDetailAuditId")]
	public long HttpExecutionDetailAuditId { get; set; } // bigint

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which execution completed.
	/// </summary>
	[Column("ExecutionCompletedAt")]
	public DateTime? ExecutionCompletedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Current or final status of the execution: Pending, InProgress, Completed, or Failed.
	/// </summary>
	[Column("ExecutionStatus", CanBeNull = false)]
	public string ExecutionStatus { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// JSON or text details captured during execution, including logs and error messages when applicable.
	/// </summary>
	[Column("ExecutionDetails")]
	public string? ExecutionDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_HttpExecutionDetailAuditsServiceResponseFilesLinks_HttpExecutionDetailAuditId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(HttpExecutionDetailAuditId), OtherKey = nameof(ServiceAppManagement.HttpExecutionDetailAudit.Id))]
	public HttpExecutionDetailAudit HttpExecutionDetailAudit { get; set; } = null!;

	/// <summary>
	/// FK_HttpExecutionDetailAuditsServiceResponseFilesLinks_ServiceResponseFiles_ServiceResponseFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceResponseFileId), OtherKey = nameof(ServiceAppManagement.ServiceResponseFile.Id))]
	public ServiceResponseFile ServiceResponseFile { get; set; } = null!;
	#endregion
}
