// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

[Table("ServiceResponseFiles")]
public partial class ServiceResponseFile
{
	/// <summary>
	/// Unique identifier for this ServiceResponseFiles record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Format of the stored file payload, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Compressed binary content stored for this record.
	/// </summary>
	[Column("CompressedData", CanBeNull = false)]
	public byte[] CompressedData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public long? UncompressedSizeBytes { get; set; } // bigint

	/// <summary>
	/// Algorithm used to compress the stored content (e.g., Zstandard, Brotli, Gzip, or none).
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// Application-managed version string (format YY.QQ.NN) used for optimistic concurrency control and change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Indicates whether this record is active and available for use (1) or soft-deleted (0).
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinkAudits_ServiceResponseFiles_ServiceResponseFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionGroupServiceRequestFileLinkAudit.ServiceResponseFileId))]
	public IEnumerable<DirectExecutionGroupServiceRequestFileLinkAudit> DirectExecutionGroupServiceRequestFileLinkAudits { get; set; } = null!;

	/// <summary>
	/// FK_HttpExecutionDetailAuditsServiceResponseFilesLinks_ServiceResponseFiles_ServiceResponseFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(HttpExecutionDetailAuditsServiceResponseFilesLink.ServiceResponseFileId))]
	public IEnumerable<HttpExecutionDetailAuditsServiceResponseFilesLink> HttpExecutionDetailAuditsServiceResponseFilesLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFileBinaryEmbeddingStoreLinks_ServiceResponseFiles backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFileBinaryEmbeddingStoreLink.ServiceResponseFileId))]
	public IEnumerable<ServiceResponseFileBinaryEmbeddingStoreLink> ServiceResponseFileBinaryEmbeddingStoreLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFileHttpExecutionDetailLinks_ServiceResponseFiles_ServiceResponseFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFileHttpExecutionDetailLink.ServiceResponseFileId))]
	public IEnumerable<ServiceResponseFileHttpExecutionDetailLink> ServiceResponseFileHttpExecutionDetailLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFilesDatabaseAudits_ServiceResponseFile_ServiceResponseFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFilesDatabaseAudit.ServiceResponseFileId))]
	public IEnumerable<ServiceResponseFilesDatabaseAudit> ServiceResponseFilesDatabaseAudits { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFiles_ServiceRequestFiles_ServiceRequestFileId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(ServiceAppManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile ServiceRequestFile { get; set; } = null!;
	#endregion
}
