// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

/// <summary>
/// Stores binary embedding links for service response files.
/// </summary>
[Table("ServiceResponseFileBinaryEmbeddingStoreLinks")]
public partial class ServiceResponseFileBinaryEmbeddingStoreLink
{
	/// <summary>
	/// Unique identifier for this ServiceResponseFileBinaryEmbeddingStoreLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId")]
	public long ServiceResponseFileId { get; set; } // bigint

	/// <summary>
	/// XML element name or JSON key used to reference this binary in the payload.
	/// </summary>
	[Column("ElementName", CanBeNull = false)]
	public string ElementName { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// XPath or JSONPath expression locating this element in the payload.
	/// </summary>
	[Column("XmlPath", CanBeNull = false)]
	public string XmlPath { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// Identifier of the related BinaryEmbeddingStores record.
	/// </summary>
	[Column("BinaryEmbeddingsStoreId")]
	public long BinaryEmbeddingsStoreId { get; set; } // bigint

	/// <summary>
	/// Logical file name for the embedded binary asset.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Additional file type general metadata for binary content.
	/// </summary>
	[Column("AdditionalDetails")]
	public string? AdditionalDetails { get; set; } // nvarchar(max)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the user who created this record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceResponseFileBinaryEmbeddingStoreLinks_BinaryEmbeddingStores
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(BinaryEmbeddingsStoreId), OtherKey = nameof(ServiceAppManagement.BinaryEmbeddingStore.Id))]
	public BinaryEmbeddingStore BinaryEmbeddingStore { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFileBinaryEmbeddingStoreLinks_ServiceResponseFiles
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceResponseFileId), OtherKey = nameof(ServiceAppManagement.ServiceResponseFile.Id))]
	public ServiceResponseFile ServiceResponseFile { get; set; } = null!;
	#endregion
}

