// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

[Table("ServiceRequestFiles")]
public partial class ServiceRequestFile
{
	/// <summary>
	/// Unique identifier for this ServiceRequestFiles record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related ServiceOperations record.
	/// </summary>
	[Column("ServiceOperationId")]
	public int ServiceOperationId { get; set; } // int

	/// <summary>
	/// Format of the stored file payload, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(250)

	/// <summary>
	/// Compressed binary content stored for this record.
	/// </summary>
	[Column("CompressedData", CanBeNull = false)]
	public byte[] CompressedData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public long? UncompressedSizeBytes { get; set; } // bigint

	/// <summary>
	/// Algorithm used to compress the stored content (e.g., Zstandard, Brotli, Gzip, or none).
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// Application-managed version string (format YY.QQ.NN) used for optimistic concurrency control and change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Indicates whether this record is active and available for use (1) or soft-deleted (0).
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionGroupServiceRequestFileLinks_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionGroupServiceRequestFileLink.ServiceRequestFileId))]
	public IEnumerable<DirectExecutionGroupServiceRequestFileLink> DirectExecutionGroupServiceRequestFileLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFileBinaryEmbeddingStoreLinks_ServiceRequestFiles backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFileBinaryEmbeddingStoreLink.ServiceRequestFileId))]
	public IEnumerable<ServiceRequestFileBinaryEmbeddingStoreLink> ServiceRequestFileBinaryEmbeddingStoreLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFiles_ServiceOperations_ServiceOperationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceOperationId), OtherKey = nameof(ServiceAppManagement.ServiceOperation.Id))]
	public ServiceOperation ServiceOperation { get; set; } = null!;

	/// <summary>
	/// FK_ServiceResponseFiles_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceResponseFile.ServiceRequestFileId))]
	public IEnumerable<ServiceResponseFile> ServiceResponseFiles { get; set; } = null!;
	#endregion
}
