// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

public partial class ServiceAppDbContext : DataConnection
{
	public ServiceAppDbContext()
	{
		InitDataContext();
	}

	public ServiceAppDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public ServiceAppDbContext(DataOptions<ServiceAppDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<BinaryEmbeddingStore>                              BinaryEmbeddingStores                              => this.GetTable<BinaryEmbeddingStore>();

	public ITable<DirectExecutionGroupAudit>                         DirectExecutionGroupAudits                         => this.GetTable<DirectExecutionGroupAudit>();

	public ITable<DirectExecutionGroupServiceRequestFileLinkAudit>   DirectExecutionGroupServiceRequestFileLinkAudits   => this.GetTable<DirectExecutionGroupServiceRequestFileLinkAudit>();

	public ITable<DirectExecutionGroupServiceRequestFileLink>        DirectExecutionGroupServiceRequestFileLinks        => this.GetTable<DirectExecutionGroupServiceRequestFileLink>();

	public ITable<DirectExecutionGroup>                              DirectExecutionGroups                              => this.GetTable<DirectExecutionGroup>();

	public ITable<HttpExecutionDetailAudit>                          HttpExecutionDetailAudits                          => this.GetTable<HttpExecutionDetailAudit>();

	public ITable<HttpExecutionDetailAuditsServiceResponseFilesLink> HttpExecutionDetailAuditsServiceResponseFilesLinks => this.GetTable<HttpExecutionDetailAuditsServiceResponseFilesLink>();

	public ITable<ServiceAppHealthHttpExecutionDetailAuditLink>      ServiceAppHealthHttpExecutionDetailAuditLinks      => this.GetTable<ServiceAppHealthHttpExecutionDetailAuditLink>();

	public ITable<ServiceApplication>                                ServiceApplications                                => this.GetTable<ServiceApplication>();

	public ITable<ServiceDefinitionSync>                             ServiceDefinitionSyncs                             => this.GetTable<ServiceDefinitionSync>();

	public ITable<ServiceOperationSchema>                            ServiceOperationSchemas                            => this.GetTable<ServiceOperationSchema>();

	public ITable<ServiceOperation>                                  ServiceOperations                                  => this.GetTable<ServiceOperation>();

	public ITable<ServiceRequestFileBinaryEmbeddingStoreLink>        ServiceRequestFileBinaryEmbeddingStoreLinks        => this.GetTable<ServiceRequestFileBinaryEmbeddingStoreLink>();

	public ITable<ServiceRequestFile>                                ServiceRequestFiles                                => this.GetTable<ServiceRequestFile>();

	public ITable<ServiceResponseFileBinaryEmbeddingStoreLink>       ServiceResponseFileBinaryEmbeddingStoreLinks       => this.GetTable<ServiceResponseFileBinaryEmbeddingStoreLink>();

	public ITable<ServiceResponseFileHttpExecutionDetailLink>        ServiceResponseFileHttpExecutionDetailLinks        => this.GetTable<ServiceResponseFileHttpExecutionDetailLink>();

	public ITable<ServiceResponseFile>                               ServiceResponseFiles                               => this.GetTable<ServiceResponseFile>();

	public ITable<ServiceResponseFilesDatabaseAudit>                 ServiceResponseFilesDatabaseAudits                 => this.GetTable<ServiceResponseFilesDatabaseAudit>();

	public ITable<SoapNamespace>                                     SoapNamespaces                                     => this.GetTable<SoapNamespace>();
}

public static partial class ExtensionMethods
{
	#region Table Extensions
	public static BinaryEmbeddingStore? Find(this ITable<BinaryEmbeddingStore> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<BinaryEmbeddingStore?> FindAsync(this ITable<BinaryEmbeddingStore> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static DirectExecutionGroupAudit? Find(this ITable<DirectExecutionGroupAudit> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionGroupAudit?> FindAsync(this ITable<DirectExecutionGroupAudit> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static DirectExecutionGroupServiceRequestFileLinkAudit? Find(this ITable<DirectExecutionGroupServiceRequestFileLinkAudit> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionGroupServiceRequestFileLinkAudit?> FindAsync(this ITable<DirectExecutionGroupServiceRequestFileLinkAudit> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static DirectExecutionGroupServiceRequestFileLink? Find(this ITable<DirectExecutionGroupServiceRequestFileLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionGroupServiceRequestFileLink?> FindAsync(this ITable<DirectExecutionGroupServiceRequestFileLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static DirectExecutionGroup? Find(this ITable<DirectExecutionGroup> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<DirectExecutionGroup?> FindAsync(this ITable<DirectExecutionGroup> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static HttpExecutionDetailAudit? Find(this ITable<HttpExecutionDetailAudit> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<HttpExecutionDetailAudit?> FindAsync(this ITable<HttpExecutionDetailAudit> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static HttpExecutionDetailAuditsServiceResponseFilesLink? Find(this ITable<HttpExecutionDetailAuditsServiceResponseFilesLink> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<HttpExecutionDetailAuditsServiceResponseFilesLink?> FindAsync(this ITable<HttpExecutionDetailAuditsServiceResponseFilesLink> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceAppHealthHttpExecutionDetailAuditLink? Find(this ITable<ServiceAppHealthHttpExecutionDetailAuditLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceAppHealthHttpExecutionDetailAuditLink?> FindAsync(this ITable<ServiceAppHealthHttpExecutionDetailAuditLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceApplication? Find(this ITable<ServiceApplication> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceApplication?> FindAsync(this ITable<ServiceApplication> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceDefinitionSync? Find(this ITable<ServiceDefinitionSync> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceDefinitionSync?> FindAsync(this ITable<ServiceDefinitionSync> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceOperationSchema? Find(this ITable<ServiceOperationSchema> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceOperationSchema?> FindAsync(this ITable<ServiceOperationSchema> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceOperation? Find(this ITable<ServiceOperation> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceOperation?> FindAsync(this ITable<ServiceOperation> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceRequestFileBinaryEmbeddingStoreLink? Find(this ITable<ServiceRequestFileBinaryEmbeddingStoreLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceRequestFileBinaryEmbeddingStoreLink?> FindAsync(this ITable<ServiceRequestFileBinaryEmbeddingStoreLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceRequestFile? Find(this ITable<ServiceRequestFile> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceRequestFile?> FindAsync(this ITable<ServiceRequestFile> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFileBinaryEmbeddingStoreLink? Find(this ITable<ServiceResponseFileBinaryEmbeddingStoreLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFileBinaryEmbeddingStoreLink?> FindAsync(this ITable<ServiceResponseFileBinaryEmbeddingStoreLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFileHttpExecutionDetailLink? Find(this ITable<ServiceResponseFileHttpExecutionDetailLink> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFileHttpExecutionDetailLink?> FindAsync(this ITable<ServiceResponseFileHttpExecutionDetailLink> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFile? Find(this ITable<ServiceResponseFile> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFile?> FindAsync(this ITable<ServiceResponseFile> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static ServiceResponseFilesDatabaseAudit? Find(this ITable<ServiceResponseFilesDatabaseAudit> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<ServiceResponseFilesDatabaseAudit?> FindAsync(this ITable<ServiceResponseFilesDatabaseAudit> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static SoapNamespace? Find(this ITable<SoapNamespace> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<SoapNamespace?> FindAsync(this ITable<SoapNamespace> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}
	#endregion
}
