// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.ServiceAppManagement;

[Table("SoapNamespaces")]
public partial class SoapNamespace
{
	/// <summary>
	/// Unique identifier for this SoapNamespaces record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related ServiceOperationSchemas record.
	/// </summary>
	[Column("ServiceOperationSchemaId")]
	public int ServiceOperationSchemaId { get; set; } // int

	/// <summary>
	/// JSON array of namespace prefix and URI pairs declared by the SOAP operation schema.
	/// </summary>
	[Column("DetailContent", CanBeNull = false)]
	public string DetailContent { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// Application-managed version string (format YY.QQ.NN) used for optimistic concurrency control and change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy")]
	public string? CreatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_SoapNamespaces_ServiceOperationSchemas_ServiceOperationSchemaId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceOperationSchemaId), OtherKey = nameof(ServiceAppManagement.ServiceOperationSchema.Id))]
	public ServiceOperationSchema ServiceOperationSchema { get; set; } = null!;
	#endregion
}
