// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.PermissionsManagement;

[Table("Roles")]
public partial class Role
{
	/// <summary>
	/// Unique identifier for this Roles record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Human-readable name of this record.
	/// </summary>
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(500)

	/// <summary>
	/// Indicates whether this is a system-defined role that cannot be deleted or modified.
	/// </summary>
	[Column("IsSystemRole")]
	public bool IsSystemRole { get; set; } // bit

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RolePermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RolePermission.RoleId))]
	public IEnumerable<RolePermission> RolePermissions { get; set; } = null!;

	/// <summary>
	/// FK_RuleSetsPermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetsPermission.RoleId))]
	public IEnumerable<RuleSetsPermission> RuleSetsPermissions { get; set; } = null!;

	/// <summary>
	/// FK_ServiceAppPermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceAppPermission.RoleId))]
	public IEnumerable<ServiceAppPermission> ServiceAppPermissions { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFilesPermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFilesPermission.RoleId))]
	public IEnumerable<ServiceRequestFilesPermission> ServiceRequestFilesPermissions { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestCasesPermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestCasesPermission.RoleId))]
	public IEnumerable<ServiceTestCasesPermission> ServiceTestCasesPermissions { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuitesPermissions_Roles_RoleId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestSuitesPermission.RoleId))]
	public IEnumerable<ServiceTestSuitesPermission> ServiceTestSuitesPermissions { get; set; } = null!;
	#endregion
}
