// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("BinaryEmbeddingsStore")]
public partial class BinaryEmbeddingsStore
{
	/// <summary>
	/// Unique identifier for this BinaryEmbeddingsStore record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// SHA-256 hash of the stored content for integrity verification.
	/// </summary>
	[Column("ContentHash", CanBeNull = false)]
	public string ContentHash { get; set; } = null!; // varchar(64)

	/// <summary>
	/// Compressed binary content stored for this record.
	/// </summary>
	[Column("CompressedData", CanBeNull = false)]
	public byte[] CompressedData { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Size of the file content before compression, in bytes.
	/// </summary>
	[Column("UncompressedSizeBytes")]
	public long UncompressedSizeBytes { get; set; } // bigint

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// Format of the stored binary content, such as XML, JSON, PDF, or BINARY.
	/// </summary>
	[Column("ContentFormat")]
	public string? ContentFormat { get; set; } // varchar(10)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_IndexingPdfFileElementMappings_BinaryEmbeddingsStore backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingPdfFileElementMapping.BinaryEmbeddingsStoreId))]
	public IEnumerable<IndexingPdfFileElementMapping> IndexingPdfFileElementMappings { get; set; } = null!;
	#endregion
}
