// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

/// <summary>
/// Maps XML file element values to their associated request or response files.
/// </summary>
[Table("IndexingXmlRequestResponseMappings")]
public partial class IndexingXmlRequestResponseMapping
{
	/// <summary>
	/// Unique identifier for this IndexingXmlRequestResponseMappings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record (nullable).
	/// </summary>
	[Column("ServiceRequestFileId")]
	public int? ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record (nullable).
	/// </summary>
	[Column("ServiceResponseFileId")]
	public long? ServiceResponseFileId { get; set; } // bigint

	/// <summary>
	/// Identifier of the related IndexingXmlFileElementValues record.
	/// </summary>
	[Column("IndexingXmlFileElementValueId")]
	public long IndexingXmlFileElementValueId { get; set; } // bigint

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	#region Associations
	/// <summary>
	/// FK_IndexingXmlRequestResponseMappings_IndexingXmlFileElementValues
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingXmlFileElementValueId), OtherKey = nameof(IndexingManagement.IndexingXmlFileElementValue.Id))]
	public IndexingXmlFileElementValue IndexingXmlFileElementValue { get; set; } = null!;
	#endregion
}

