// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

/// <summary>
/// Stores actual values of JSON file elements for indexing. Denormalized for faster search.
/// </summary>
[Table("IndexingJsonFileElementValues")]
public partial class IndexingJsonFileElementValue
{
	/// <summary>
	/// Unique identifier for this IndexingJsonFileElementValues record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related IndexingJsonFileElements record.
	/// </summary>
	[Column("IndexingJsonFileElementId")]
	public long IndexingJsonFileElementId { get; set; } // bigint

	/// <summary>
	/// Scalar value of the indexed JSON element.
	/// </summary>
	[Column("ElementValue", CanBeNull = false)]
	public string ElementValue { get; set; } = null!; // nvarchar(1024)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	#region Associations
	/// <summary>
	/// FK_IndexingJsonFileElementValues_IndexingJsonFileElements
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingJsonFileElementId), OtherKey = nameof(IndexingManagement.IndexingJsonFileElement.Id))]
	public IndexingJsonFileElement IndexingJsonFileElement { get; set; } = null!;

	/// <summary>
	/// FK_IndexingJsonRequestResponseMappings_IndexingJsonFileElementValues backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingJsonRequestResponseMapping.IndexingJsonFileElementValueId))]
	public IEnumerable<IndexingJsonRequestResponseMapping> IndexingJsonRequestResponseMappings { get; set; } = null!;
	#endregion
}

