// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingFileElementType")]
public partial class IndexingFileElementType
{
	/// <summary>
	/// Unique identifier for this IndexingFileElementType record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Source type of the element, such as XML or JSON.
	/// </summary>
	[Column("ElementType", CanBeNull = false)]
	public string ElementType { get; set; } = null!; // varchar(10)

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(200)
}
