// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingJsonFileElementMappings")]
public partial class IndexingJsonFileElementMapping
{
	/// <summary>
	/// Unique identifier for this IndexingJsonFileElementMappings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related ServiceRequestFiles record.
	/// </summary>
	[Column("RequestFileId")]
	public int? RequestFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ResponseFileId")]
	public int? ResponseFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related IndexingJsonFileElementSearch record.
	/// </summary>
	[Column("IndexingJsonFileElementSearchId")]
	public long IndexingJsonFileElementSearchId { get; set; } // bigint

	#region Associations
	/// <summary>
	/// FK_IndexingJsonFileElementMappings_IndexingJsonFileElementSearch
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingJsonFileElementSearchId), OtherKey = nameof(IndexingManagement.IndexingJsonFileElementSearch.Id))]
	public IndexingJsonFileElementSearch IndexingJsonFileElementSearch { get; set; } = null!;
	#endregion
}
