// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingPdfFileElementSearch")]
public partial class IndexingPdfFileElementSearch
{
	/// <summary>
	/// Unique identifier for this IndexingPdfFileElementSearch record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related IndexingPdfFileElements record.
	/// </summary>
	[Column("IndexingPdfFileElementId")]
	public long IndexingPdfFileElementId { get; set; } // bigint

	/// <summary>
	/// Scalar value of the indexed element.
	/// </summary>
	[Column("ElementValue", CanBeNull = false)]
	public string ElementValue { get; set; } = null!; // nvarchar(800)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_IndexingPdfFileElementMappings_IndexingPdfFileElementSearch backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingPdfFileElementMapping.IndexingPdfFileElementSearchId))]
	public IEnumerable<IndexingPdfFileElementMapping> IndexingPdfFileElementMappings { get; set; } = null!;

	/// <summary>
	/// FK_IndexingPdfFileElementSearch_IndexingPdfFileElements
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingPdfFileElementId), OtherKey = nameof(IndexingManagement.IndexingPdfFileElement.Id))]
	public IndexingPdfFileElement IndexingPdfFileElement { get; set; } = null!;
	#endregion
}
