// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingXmlFileElementMappings")]
public partial class IndexingXmlFileElementMapping
{
	/// <summary>
	/// Unique identifier for this IndexingXmlFileElementMappings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related service request file record.
	/// </summary>
	[Column("RequestFileId")]
	public int? RequestFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related service response file record.
	/// </summary>
	[Column("ResponseFileId")]
	public int? ResponseFileId { get; set; } // int

	/// <summary>
	/// Identifier of the related IndexingXmlFileElements record.
	/// </summary>
	[Column("ElementId")]
	public long ElementId { get; set; } // bigint

	#region Associations
	/// <summary>
	/// FK_IndexingXmlFileElementMappings_IndexingXmlFileElements
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ElementId), OtherKey = nameof(IndexingXmlFileElement.ElementId))]
	public IndexingXmlFileElement Element { get; set; } = null!;
	#endregion
}
