// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingXmlFileElements")]
public partial class IndexingXmlFileElement
{
	/// <summary>
	/// Identifier of the indexed element.
	/// </summary>
	[Column("ElementId", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long ElementId { get; set; } // bigint

	/// <summary>
	/// XPath key path of the indexed XML element.
	/// </summary>
	[Column("XPathKeyPath", CanBeNull = false)]
	public string XPathKeyPath { get; set; } = null!; // varchar(400)

	/// <summary>
	/// Scalar value of the indexed element.
	/// </summary>
	[Column("ElementValue", CanBeNull = false)]
	public string ElementValue { get; set; } = null!; // nvarchar(450)

	/// <summary>
	/// SHA-256 hash used for global single-instance element deduplication.
	/// </summary>
	[Column("ValueHash", CanBeNull = false)]
	public byte[] ValueHash { get; set; } = null!; // binary(32)

	#region Associations
	/// <summary>
	/// FK_IndexingXmlFileElementMappings_IndexingXmlFileElements backreference
	/// </summary>
	[Association(ThisKey = nameof(ElementId), OtherKey = nameof(IndexingXmlFileElementMapping.ElementId))]
	public IEnumerable<IndexingXmlFileElementMapping> IndexingXmlFileElementMappings { get; set; } = null!;
	#endregion
}
