// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

public partial class IndexingDbContext : DataConnection
{
	public IndexingDbContext()
	{
		InitDataContext();
	}

	public IndexingDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public IndexingDbContext(DataOptions<IndexingDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<IndexingJsonFileElementValue>       IndexingJsonFileElementValues       => this.GetTable<IndexingJsonFileElementValue>();

	public ITable<IndexingJsonFileElement>            IndexingJsonFileElements            => this.GetTable<IndexingJsonFileElement>();

	public ITable<IndexingJsonRequestResponseMapping> IndexingJsonRequestResponseMappings => this.GetTable<IndexingJsonRequestResponseMapping>();

	public ITable<IndexingPdfFileElementMapping>      IndexingPdfFileElementMappings      => this.GetTable<IndexingPdfFileElementMapping>();

	public ITable<IndexingPdfFileElementValue>        IndexingPdfFileElementValues        => this.GetTable<IndexingPdfFileElementValue>();

	public ITable<IndexingPdfFileElement>             IndexingPdfFileElements             => this.GetTable<IndexingPdfFileElement>();

	public ITable<IndexingServiceRequestFileStatus>   IndexingServiceRequestFileStatuses  => this.GetTable<IndexingServiceRequestFileStatus>();

	public ITable<IndexingServiceResponseFileStatus>  IndexingServiceResponseFileStatuses => this.GetTable<IndexingServiceResponseFileStatus>();

	public ITable<IndexingXmlFileElementValue>        IndexingXmlFileElementValues        => this.GetTable<IndexingXmlFileElementValue>();

	public ITable<IndexingXmlFileElement>             IndexingXmlFileElements             => this.GetTable<IndexingXmlFileElement>();

	public ITable<IndexingXmlRequestResponseMapping>  IndexingXmlRequestResponseMappings  => this.GetTable<IndexingXmlRequestResponseMapping>();
}

public static partial class ExtensionMethods
{
	#region Table Extensions
	public static IndexingJsonFileElementValue? Find(this ITable<IndexingJsonFileElementValue> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingJsonFileElementValue?> FindAsync(this ITable<IndexingJsonFileElementValue> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingJsonFileElement? Find(this ITable<IndexingJsonFileElement> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingJsonFileElement?> FindAsync(this ITable<IndexingJsonFileElement> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingJsonRequestResponseMapping? Find(this ITable<IndexingJsonRequestResponseMapping> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingJsonRequestResponseMapping?> FindAsync(this ITable<IndexingJsonRequestResponseMapping> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingPdfFileElementMapping? Find(this ITable<IndexingPdfFileElementMapping> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingPdfFileElementMapping?> FindAsync(this ITable<IndexingPdfFileElementMapping> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingPdfFileElementValue? Find(this ITable<IndexingPdfFileElementValue> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingPdfFileElementValue?> FindAsync(this ITable<IndexingPdfFileElementValue> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingPdfFileElement? Find(this ITable<IndexingPdfFileElement> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingPdfFileElement?> FindAsync(this ITable<IndexingPdfFileElement> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingServiceRequestFileStatus? Find(this ITable<IndexingServiceRequestFileStatus> table, int serviceRequestFileId)
	{
		return table.FirstOrDefault(e => e.ServiceRequestFileId == serviceRequestFileId);
	}

	public static Task<IndexingServiceRequestFileStatus?> FindAsync(this ITable<IndexingServiceRequestFileStatus> table, int serviceRequestFileId, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.ServiceRequestFileId == serviceRequestFileId, cancellationToken);
	}

	public static IndexingServiceResponseFileStatus? Find(this ITable<IndexingServiceResponseFileStatus> table, long serviceResponseFileId)
	{
		return table.FirstOrDefault(e => e.ServiceResponseFileId == serviceResponseFileId);
	}

	public static Task<IndexingServiceResponseFileStatus?> FindAsync(this ITable<IndexingServiceResponseFileStatus> table, long serviceResponseFileId, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.ServiceResponseFileId == serviceResponseFileId, cancellationToken);
	}

	public static IndexingXmlFileElementValue? Find(this ITable<IndexingXmlFileElementValue> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingXmlFileElementValue?> FindAsync(this ITable<IndexingXmlFileElementValue> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingXmlFileElement? Find(this ITable<IndexingXmlFileElement> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingXmlFileElement?> FindAsync(this ITable<IndexingXmlFileElement> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static IndexingXmlRequestResponseMapping? Find(this ITable<IndexingXmlRequestResponseMapping> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<IndexingXmlRequestResponseMapping?> FindAsync(this ITable<IndexingXmlRequestResponseMapping> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}
	#endregion
}
