// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingJsonFileElements")]
public partial class IndexingJsonFileElement
{
	/// <summary>
	/// Unique identifier for this IndexingJsonFileElements record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Name or key of the indexed element within the file.
	/// </summary>
	[Column("ElementName", CanBeNull = false)]
	public string ElementName { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// JSON path key path of the indexed JSON element.
	/// </summary>
	[Column("JsonPath", CanBeNull = false)]
	public string JsonPath { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// Data type of the element value.
	/// </summary>
	[Column("ValueType", CanBeNull = false)]
	public string ValueType { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("UpdatedAt")]
	public DateTime? UpdatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_IndexingJsonFileElementSearch_IndexingJsonFileElements backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingJsonFileElementSearch.IndexingJsonFileElementId))]
	public IEnumerable<IndexingJsonFileElementSearch> IndexingJsonFileElementSearches { get; set; } = null!;
	#endregion
}
