// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingPdfFileElements")]
public partial class IndexingPdfFileElement
{
	/// <summary>
	/// Unique identifier for this IndexingPdfFileElements record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Name or key of the indexed element within the file.
	/// </summary>
	[Column("ElementName", CanBeNull = false)]
	public string ElementName { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// Source type of the element, such as Text, Image, Table, or Field (PDF) or XML/JSON.
	/// </summary>
	[Column("ElementType", CanBeNull = false)]
	public string ElementType { get; set; } = null!; // nvarchar(100)

	/// <summary>
	/// Page number within the PDF document where the element was found.
	/// </summary>
	[Column("PageNumber")]
	public int PageNumber { get; set; } // int

	/// <summary>
	/// Bounding rectangle coordinates of the PDF element on the page.
	/// </summary>
	[Column("BoundingRectangle", CanBeNull = false)]
	public string BoundingRectangle { get; set; } = null!; // nvarchar(400)

	/// <summary>
	/// Data type of the element value (e.g., String, Number, Boolean, Array, Object, Null).
	/// </summary>
	[Column("ValueType", CanBeNull = false)]
	public string ValueType { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	#region Associations
	/// <summary>
	/// FK_IndexingPdfFileElementValues_IndexingPdfFileElements backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingPdfFileElementValue.IndexingPdfFileElementId))]
	public IEnumerable<IndexingPdfFileElementValue> IndexingPdfFileElementValues { get; set; } = null!;
	#endregion
}
