// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingXmlFileElementSearch")]
public partial class IndexingXmlFileElementSearch
{
	/// <summary>
	/// Unique identifier for this IndexingXmlFileElementSearch record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related IndexingXmlFileElements record.
	/// </summary>
	[Column("IndexingXmlFileElementId")]
	public long IndexingXmlFileElementId { get; set; } // bigint

	/// <summary>
	/// Scalar value of the indexed element.
	/// </summary>
	[Column("ElementValue", CanBeNull = false)]
	public string ElementValue { get; set; } = null!; // nvarchar(800)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_IndexingXmlFileElementMappings_IndexingXmlFileElementSearch backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(IndexingXmlFileElementMapping.IndexingXmlFileElementSearchId))]
	public IEnumerable<IndexingXmlFileElementMapping> IndexingXmlFileElementMappings { get; set; } = null!;

	/// <summary>
	/// FK_IndexingXmlFileElementSearch_IndexingXmlFileElements
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingXmlFileElementId), OtherKey = nameof(IndexingManagement.IndexingXmlFileElement.Id))]
	public IndexingXmlFileElement IndexingXmlFileElement { get; set; } = null!;
	#endregion
}
