// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingJsonFileElements")]
public partial class IndexingJsonFileElement
{
	/// <summary>
	/// Identifier of the indexed element.
	/// </summary>
	[Column("ElementId", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long ElementId { get; set; } // bigint

	/// <summary>
	/// JSON path key path of the indexed JSON element.
	/// </summary>
	[Column("JsonPathKeyPath", CanBeNull = false)]
	public string JsonPathKeyPath { get; set; } = null!; // varchar(400)

	/// <summary>
	/// Scalar value of the indexed element.
	/// </summary>
	[Column("ElementValue", CanBeNull = false)]
	public string ElementValue { get; set; } = null!; // nvarchar(450)

	/// <summary>
	/// Data type of the element value.
	/// </summary>
	[Column("ValueType", CanBeNull = false)]
	public string ValueType { get; set; } = null!; // varchar(20)

	/// <summary>
	/// SHA-256 hash used for global single-instance element deduplication.
	/// </summary>
	[Column("ValueHash", CanBeNull = false)]
	public byte[] ValueHash { get; set; } = null!; // binary(32)

	#region Associations
	/// <summary>
	/// FK_IndexingJsonFileElementMappings_IndexingJsonFileElements backreference
	/// </summary>
	[Association(ThisKey = nameof(ElementId), OtherKey = nameof(IndexingJsonFileElementMapping.ElementId))]
	public IEnumerable<IndexingJsonFileElementMapping> IndexingJsonFileElementMappings { get; set; } = null!;
	#endregion
}
