// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

/// <summary>
/// Tracks the asynchronous background element-indexing state for request files.
/// Primary key is ServiceRequestFileId (no identity column).
/// </summary>
[Table("IndexingServiceRequestFileStatus")]
public partial class IndexingServiceRequestFileStatus
{
	/// <summary>
	/// Identifier of the related ServiceRequestFiles record (also the primary key).
	/// </summary>
	[Column("ServiceRequestFileId", IsPrimaryKey = true)]
	public int ServiceRequestFileId { get; set; } // int

	/// <summary>
	/// Current indexing status (Pending, Processing, Completed, Failed).
	/// </summary>
	[Column("IndexingStatus", CanBeNull = false)]
	public string IndexingStatus { get; set; } = null!; // varchar(20)

	/// <summary>
	/// Failure reason if indexing failed.
	/// </summary>
	[Column("IndexingFailureReason")]
	public string? IndexingFailureReason { get; set; } // nvarchar(max)

	/// <summary>
	/// Date and time at which the last successful indexing completed.
	/// </summary>
	[Column("LastIndexedAt")]
	public DateTime? LastIndexedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime2(3)
}

