// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("IndexingPdfFileElementMappings")]
public partial class IndexingPdfFileElementMapping
{
	/// <summary>
	/// Unique identifier for this IndexingPdfFileElementMappings record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint

	/// <summary>
	/// Identifier of the related BinaryEmbeddingsStore record.
	/// </summary>
	[Column("BinaryEmbeddingsStoreId")]
	public int? BinaryEmbeddingsStoreId { get; set; } // int

	/// <summary>
	/// Identifier of the related IndexingPdfFileElementSearch record.
	/// </summary>
	[Column("IndexingPdfFileElementSearchId")]
	public long IndexingPdfFileElementSearchId { get; set; } // bigint

	#region Associations
	/// <summary>
	/// FK_IndexingPdfFileElementMappings_BinaryEmbeddingsStore
	/// </summary>
	[Association(ThisKey = nameof(BinaryEmbeddingsStoreId), OtherKey = nameof(IndexingManagement.BinaryEmbeddingsStore.Id))]
	public BinaryEmbeddingsStore? BinaryEmbeddingsStore { get; set; }

	/// <summary>
	/// FK_IndexingPdfFileElementMappings_IndexingPdfFileElementSearch
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(IndexingPdfFileElementSearchId), OtherKey = nameof(IndexingManagement.IndexingPdfFileElementSearch.Id))]
	public IndexingPdfFileElementSearch IndexingPdfFileElementSearch { get; set; } = null!;
	#endregion
}
