// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.IndexingManagement;

[Table("ServiceResponseIndexingStatus")]
public partial class ServiceResponseIndexingStatus
{
	/// <summary>
	/// Identifier of the related ServiceResponseFiles record.
	/// </summary>
	[Column("ServiceResponseFileId", IsPrimaryKey = true)]
	public int ServiceResponseFileId { get; set; } // int

	/// <summary>
	/// Background element-indexing status of the file: Pending, Processing, Completed, or Failed.
	/// </summary>
	[Column("IndexingStatus", CanBeNull = false)]
	public string IndexingStatus { get; set; } = null!; // varchar(20)

	/// <summary>
	/// Error message and stack trace captured when indexing fails.
	/// </summary>
	[Column("IndexingFailureReason")]
	public string? IndexingFailureReason { get; set; } // nvarchar(max)

	/// <summary>
	/// Date and time at which background parsing last completed.
	/// </summary>
	[Column("LastIndexedAt")]
	public DateTime? LastIndexedAt { get; set; } // datetime

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
}
