// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapExecutionLogs")]
public partial class SoapExecutionLogEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("ExecutionFileId", CanBeNull = false)]
	public string ExecutionFileId { get; set; } = null!;

	[Column("Timestamp")]
	public string? Timestamp { get; set; }

	[Column("Type")]
	public string? Type { get; set; }

	[Column("Message")]
	public string? Message { get; set; }
}