// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapParsedFields")]
public partial class SoapParsedFieldEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("ExecutionFileId", CanBeNull = false)]
	public string ExecutionFileId { get; set; } = null!;

	[Column("Name")]
	public string? Name { get; set; }

	[Column("Source")]
	public string? Source { get; set; }

	[Column("Path")]
	public string? Path { get; set; }

	[Column("Value")]
	public string? Value { get; set; }

	[Column("IsEmbedded")]
	public bool IsEmbedded { get; set; }

	[Column("DecodedPreview")]
	public string? DecodedPreview { get; set; }
}