// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapTestCases")]
public partial class SoapTestCaseEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!;

	[Column("Description")]
	public string? Description { get; set; }

	[Column("AppName", CanBeNull = false)]
	public string AppName { get; set; } = null!;

	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!;

	[Column("Enabled")]
	public bool Enabled { get; set; }

	[Column("CreatedBy")]
	public string? CreatedBy { get; set; }

	[Column("CreatedAt")]
	public string? CreatedAt { get; set; }

	[Column("UpdatedBy")]
	public string? UpdatedBy { get; set; }

	[Column("UpdatedAt")]
	public string? UpdatedAt { get; set; }
}