// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapExecutionGroups")]
public partial class SoapExecutionGroupEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("StartedAt", CanBeNull = false)]
	public string StartedAt { get; set; } = null!;

	[Column("FinishedAt")]
	public string? FinishedAt { get; set; }

	[Column("TriggeredBy")]
	public string? TriggeredBy { get; set; }

	[Column("Status", CanBeNull = false)]
	public string Status { get; set; } = null!;

	[Column("DurationMs")]
	public long? DurationMs { get; set; }
}