// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapExtractors")]
public partial class SoapExtractorEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("TestCaseId", CanBeNull = false)]
	public string TestCaseId { get; set; } = null!;

	[Column("Name")]
	public string? Name { get; set; }

	[Column("Source")]
	public string? Source { get; set; }

	[Column("Type")]
	public string? Type { get; set; }

	[Column("Path")]
	public string? Path { get; set; }

	[Column("ExpectedValue")]
	public string? ExpectedValue { get; set; }
}