// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub SOAP management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.SoapManagement;

[Table("SoapRequestFiles")]
public partial class SoapRequestFileEntity
{
	[Column("Id", IsPrimaryKey = true)]
	public string Id { get; set; } = null!;

	[Column("AppName", CanBeNull = false)]
	public string AppName { get; set; } = null!;

	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!;

	[Column("ApiPath")]
	public string? ApiPath { get; set; }

	[Column("Verb")]
	public string? Verb { get; set; }

	[Column("Description")]
	public string? Description { get; set; }

	[Column("Status")]
	public string? Status { get; set; }

	[Column("CreatedBy")]
	public string? CreatedBy { get; set; }

	[Column("CreatedAt")]
	public string? CreatedAt { get; set; }

	[Column("UpdatedBy")]
	public string? UpdatedBy { get; set; }

	[Column("UpdatedAt")]
	public string? UpdatedAt { get; set; }

	[Column("Content")]
	public string? Content { get; set; }
}