/*
    Table: ServiceResponseFiles
    Description: Stores the response files generated by services, including their metadata and binary data.
*/
CREATE TABLE [dbo].[ServiceResponseFiles] (
    -- Primary Key, Identity Column and Unique identifier
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
    -- Public Identifier for UI/Secure Operations (GUID)
    [PublicId] UNIQUEIDENTIFIER NOT NULL 
        CONSTRAINT DF_ServiceResponseFiles_PublicId DEFAULT NEWID(),
    -- Foreign key to the ServiceRequestFiles table
    [ServiceRequestFileId] INT NOT NULL,
    -- File format, e.g., 'XML', 'JSON', 'PDF', 'BINARY'
    [FileFormat] VARCHAR(10) NULL,
    -- File name, e.g., 'request.xml', 'response.json'
    [Name] NVARCHAR(250) NOT NULL,
    -- Compressed file data
    [CompressedData] VARBINARY(MAX) NOT NULL,
    -- Uncompressed size of the file in bytes
    [UncompressedSizeBytes] BIGINT NULL,
    -- Compression algorithm used for the file, e.g., 'Zstandard', 'Brotli', 'Gzip', 'none'
    [CompressionAlgorithmType] VARCHAR(50) NULL,
    -- Record version for optimistic concurrency control, formatted as 'YY.QQ.NN', e.g., '24.10.01'
    [RecordVersion] VARCHAR(50) NOT NULL
        CONSTRAINT DF_ServiceResponseFiles_RecordVersion DEFAULT ([dbo].[fn_CalculateVersion](NULL)),
    -- Indicates if the service response file record is currently active
    [IsActive] BIT NOT NULL CONSTRAINT DF_ServiceResponseFiles_IsActive DEFAULT 1,
    -- Timestamps for auditing created and last updated
    [CreatedAt] DATETIME2(3) NOT NULL CONSTRAINT DF_ServiceResponseFiles_CreatedAt DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(20) NOT NULL,

    CONSTRAINT PK_ServiceResponseFiles PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT UQ_ServiceResponseFiles_PublicId UNIQUE ([PublicId] ASC),
    
    CONSTRAINT CK_ServiceResponseFiles_Format
        CHECK ([FileFormat] IS NULL OR [FileFormat] IN ('XML','JSON','PDF','BINARY')),
    CONSTRAINT CK_ServiceResponseFiles_CompressionAlgorithmType
        CHECK ([CompressionAlgorithmType] IS NULL OR [CompressionAlgorithmType] IN ('Zstandard', 'Brotli', 'Gzip', 'none')),
    CONSTRAINT CK_ServiceResponseFiles_RecordVersionFormat
        CHECK ([RecordVersion] LIKE '[0-9][0-9].[0-9][0-9].[0-9][0-9]'),

    -- Foreign Key Constraints
    CONSTRAINT FK_ServiceResponseFiles_ServiceRequestFiles_ServiceRequestFileId
        FOREIGN KEY ([ServiceRequestFileId]) REFERENCES [dbo].[ServiceRequestFiles]([Id]),
    CONSTRAINT FK_ServiceResponseFiles_Users_CreatedBy
        FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users]([UserId])
);
GO

CREATE NONCLUSTERED INDEX IX_ServiceResponseFiles_ServiceRequestFileId
    ON [dbo].[ServiceResponseFiles]([ServiceRequestFileId] ASC)
GO

CREATE NONCLUSTERED INDEX IX_ServiceResponseFiles_CreatedAt
    ON [dbo].[ServiceResponseFiles]([CreatedAt] ASC)
GO
