// <auto-generated>
// Generated from v_LatestServiceApplicationsWithAuth
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class LatestServiceApplicationWithAuthView
{
    public string ServiceApplicationId { get; set; } = string.Empty;
    public long InternalId { get; set; }
    public string ServiceType { get; set; } = string.Empty;
    public string ServiceApplicationName { get; set; } = string.Empty;
    public string? BaseUrl { get; set; }
    public string? DefinitionType { get; set; }
    public string? DefinitionRelativeUrl { get; set; }
    public string? HealthcheckRelativeUrl { get; set; }
    public string? Description { get; set; }
    public bool? IsActive { get; set; }
    public int? ServiceApplicationVersion { get; set; }
    public DateTime? ServiceAppCreatedAt { get; set; }
    public string? ServiceAppCreatedBy { get; set; }
    public DateTime? ServiceAppLastUpdatedAt { get; set; }
    public string? ServiceAppLastUpdatedBy { get; set; }
    public string? AuthenticationId { get; set; }
    public string? AuthenticationName { get; set; }
    public string? AuthenticationType { get; set; }
    public string? EncryptionAlgorithmType { get; set; }
    public int? AuthenticationVersion { get; set; }
    public DateTime? AuthCreatedAt { get; set; }
    public string? AuthCreatedBy { get; set; }
    public DateTime? AuthLastUpdatedAt { get; set; }
    public string? AuthLastUpdatedBy { get; set; }
    public bool HasAuthentication { get; set; }
}
