// <auto-generated>
// Generated from v_ServiceTestCasesWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceTestCaseWithDetailsView
{
    public long TestCaseId { get; set; }
    public string TestCaseName { get; set; } = string.Empty;
    public long ServiceRequestFileId { get; set; }
    public bool? TestCaseIsActive { get; set; }
    public int? TestCaseVersion { get; set; }
    public DateTime? TestCaseCreatedAt { get; set; }
    public string? TestCaseCreatedBy { get; set; }
    public DateTime? TestCaseLastUpdatedAt { get; set; }
    public string? TestCaseLastUpdatedBy { get; set; }
    public string? RequestFileName { get; set; }
    public string? RequestFileFormat { get; set; }
    public bool? RequestIsBase { get; set; }
    public long? RequestSize { get; set; }
    public string? LinkedSuites { get; set; }
    public int SuiteCount { get; set; }
    public string? LinkedRuleSets { get; set; }
    public int RuleSetCount { get; set; }
    public string? LastExecution { get; set; }
}
