// <auto-generated>
// Generated from v_ServiceResponseFilesWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class ServiceResponseFileWithDetailsView
{
    public long ResponseFileId { get; set; }
    public long ServiceRequestFileId { get; set; }
    public string? FileFormat { get; set; }
    public string ResponseFileName { get; set; } = string.Empty;
    public bool IsBaseSnapshot { get; set; }
    public long? ParentBaseId { get; set; }
    public long? ParentDeltaId { get; set; }
    public int? DeltaDepth { get; set; }
    public long? ResponseSize { get; set; }
    public string? ResponseCompression { get; set; }
    public string? ResponseFileHash { get; set; }
    public int? ResponseRecordVersion { get; set; }
    public bool ResponseIsActive { get; set; }
    public DateTime ResponseCreatedAt { get; set; }
    public string ResponseCreatedBy { get; set; } = string.Empty;
    public DateTime? ResponseLastUpdatedAt { get; set; }
    public string? ResponseLastUpdatedBy { get; set; }
    public long RequestFileId { get; set; }
    public string RequestFileName { get; set; } = string.Empty;
    public string? RequestFileFormat { get; set; }
    public bool? RequestIsBase { get; set; }
    public long? RequestSize { get; set; }
    public string? RequestFileHash { get; set; }
    public long OperationId { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public string? HttpMethod { get; set; }
    public string? EndpointOrAction { get; set; }
    public string? OperationDescription { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public string HumanReadableSize { get; set; } = string.Empty;
    public string FileTypeDescription { get; set; } = string.Empty;
    public string? ParentBaseName { get; set; }
    public string? ParentDeltaName { get; set; }
    public string HashShort { get; set; } = string.Empty;
    public string StatusDescription { get; set; } = string.Empty;
    public int AgeDays { get; set; }
    public string RequestResponsePair { get; set; } = string.Empty;
}
