// <auto-generated>
// Generated from v_SoapNamespacesSummary
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class SoapNamespacesSummaryView
{
    public long OperationId { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public bool? OperationIsActive { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public int TotalNamespaces { get; set; }
    public int CompressionTypesUsed { get; set; }
    public long? TotalUncompressedSize { get; set; }
    public long? AvgUncompressedSize { get; set; }
    public DateTime? LatestNamespaceCreated { get; set; }
    public DateTime? LatestNamespaceUpdated { get; set; }
    public string? LatestNamespaceCreatedBy { get; set; }
    public string CompressionTypes { get; set; } = string.Empty;
    public int UniqueHashes { get; set; }
}
