// <auto-generated>
// Generated from v_SoapNamespacesWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Views;

public class SoapNamespacesWithDetailsView
{
    public long NamespaceId { get; set; }
    public long ServiceOperationSchemaId { get; set; }
    public long? UncompressedSizeBytes { get; set; }
    public string? CompressionAlgorithmType { get; set; }
    public string? ContentHash { get; set; }
    public int? NamespaceRecordVersion { get; set; }
    public DateTime? NamespaceCreatedAt { get; set; }
    public string? NamespaceCreatedBy { get; set; }
    public DateTime? NamespaceLastUpdatedAt { get; set; }
    public string? NamespaceLastUpdatedBy { get; set; }
    public long OperationId { get; set; }
    public string OperationName { get; set; } = string.Empty;
    public string? EndpointOrAction { get; set; }
    public string? HttpMethod { get; set; }
    public bool? OperationIsActive { get; set; }
    public int? OperationRecordVersion { get; set; }
    public string? InputRootElementName { get; set; }
    public string? OutputRootElementName { get; set; }
    public string? TargetNamespace { get; set; }
    public int? SchemaRecordVersion { get; set; }
    public DateTime? SchemaCreatedAt { get; set; }
    public string? SchemaCreatedBy { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public string? BaseUrl { get; set; }
    public bool? ServiceIsActive { get; set; }
    public string HumanReadableSize { get; set; } = string.Empty;
    public string NamespaceStatus { get; set; } = string.Empty;
    public string ContentHashShort { get; set; } = string.Empty;
    public int DaysSinceCreation { get; set; }
    public int DaysSinceLastUpdate { get; set; }
}
