// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.RuleManagement;

[Table("RuleContextObjects")]
public partial class RuleContextObject
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("ContextName", CanBeNull = false)]
	public string ContextName { get; set; } = null!; // nvarchar(100)
	[Column("RuleTypeId", CanBeNull = false)]
	public string RuleTypeId { get; set; } = null!; // nvarchar(255)
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(500)
	[Column("IsActive")]
	public bool? IsActive { get; set; } // bit
	[Column("CreatedDate")]
	public DateTime? CreatedDate { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_RuleSetContextObjectLinks_RuleContextObjects backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetContextObjectLink.RuleContextObjectId))]
	public IEnumerable<RuleSetContextObjectLink> RuleSetContextObjectLinks { get; set; } = null!;

	/// <summary>
	/// FK_RuleSets_RuleContextObjects backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSet.OutputTypeId))]
	public IEnumerable<RuleSet> RuleSets { get; set; } = null!;
	#endregion
}
