// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.RuleManagement;

[Table("RuleExecutionLogs")]
public partial class RuleExecutionLog
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("RuleSetId")]
	public int RuleSetId { get; set; } // int
	[Column("ContextSnapshot", CanBeNull = false)]
	public string ContextSnapshot { get; set; } = null!; // nvarchar(max)
	[Column("IsSuccess")]
	public bool IsSuccess { get; set; } // bit
	[Column("Result")]
	public string? Result { get; set; } // nvarchar(max)
	[Column("ErrorMessage")]
	public string? ErrorMessage { get; set; } // nvarchar(max)
	[Column("ExecutionTimeMs")]
	public int? ExecutionTimeMs { get; set; } // int
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleExecutionLogs_RuleSets
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleSetId), OtherKey = nameof(RuleManagement.RuleSet.Id))]
	public RuleSet RuleSet { get; set; } = null!;
	#endregion
}
