// <auto-generated>
// Generated from GetBinaryEmbeddingUsage
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.IndexingManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Models;

namespace OrbitHub.Data.Repositories.IndexingManagement.Repositories;

public class GetBinaryEmbeddingUsageRepository
{
    private readonly IndexingDbContext _ctx;

    public GetBinaryEmbeddingUsageRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<GetBinaryEmbeddingUsageOutput>> ExecuteAsync(GetBinaryEmbeddingUsageInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetBinaryEmbeddingUsageOutput>(
                    "[dbo].[usp_GetBinaryEmbeddingUsage]",
                new DataParameter("@FileHash", input.FileHash)
                )).ToList();
                return RepositoryResult<GetBinaryEmbeddingUsageOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<GetBinaryEmbeddingUsageOutput>.Fail(ex.Message);
        }
    }
}