// <auto-generated>
// Generated from GetFilesByElement
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.IndexingManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.IndexingManagement.Models;

namespace OrbitHub.Data.Repositories.IndexingManagement.Repositories;

public class GetFilesByElementRepository
{
    private readonly IndexingDbContext _ctx;

    public GetFilesByElementRepository(IndexingDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetFilesByElementOutput>>> ExecuteAsync(GetFilesByElementInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetFilesByElementOutput>(
                    "[dbo].[usp_GetFilesByElement]",
                new DataParameter("@ElementType", input.ElementType),
                new DataParameter("@KeyPath", input.KeyPath),
                new DataParameter("@ElementValue", input.ElementValue),
                new DataParameter("@IncludeContent", input.IncludeContent)
                )).ToList();
                return RepositoryResult<List<GetFilesByElementOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetFilesByElementOutput>>.Fail(ex.Message);
        }
    }
}