// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

[Table("RuleExecutionLogs")]
public partial class RuleExecutionLog
{
	/// <summary>
	/// Unique identifier for this RuleExecutionLogs record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related RuleSets record.
	/// </summary>
	[Column("RuleSetId")]
	public int RuleSetId { get; set; } // int

	/// <summary>
	/// Compressed binary content of the rule input context.
	/// </summary>
	[Column("InputCompressedContent", CanBeNull = false)]
	public byte[] InputCompressedContent { get; set; } = null!; // varbinary(max)

	/// <summary>
	/// Compressed binary content of the rule output result.
	/// </summary>
	[Column("OutputCompressedContent")]
	public byte[]? OutputCompressedContent { get; set; } // varbinary(max)

	/// <summary>
	/// Size of the rule input content before compression, in bytes.
	/// </summary>
	[Column("InputUncompressedSizeBytes")]
	public int? InputUncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Size of the rule output content before compression, in bytes.
	/// </summary>
	[Column("OutputUncompressedSizeBytes")]
	public int? OutputUncompressedSizeBytes { get; set; } // int

	/// <summary>
	/// Algorithm used to compress the stored content.
	/// </summary>
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)

	/// <summary>
	/// SHA-256 hash of the rule input content.
	/// </summary>
	[Column("InputContentHash")]
	public string? InputContentHash { get; set; } // varchar(64)

	/// <summary>
	/// SHA-256 hash of the rule output content.
	/// </summary>
	[Column("OutputContentHash")]
	public string? OutputContentHash { get; set; } // varchar(64)

	/// <summary>
	/// Indicates whether the execution completed successfully.
	/// </summary>
	[Column("IsSuccess")]
	public bool IsSuccess { get; set; } // bit

	/// <summary>
	/// Error message captured when execution fails.
	/// </summary>
	[Column("ErrorMessage")]
	public string? ErrorMessage { get; set; } // nvarchar(max)

	/// <summary>
	/// Rule execution duration in milliseconds.
	/// </summary>
	[Column("ExecutionTimeMs")]
	public int? ExecutionTimeMs { get; set; } // int

	/// <summary>
	/// Date and time at which execution started.
	/// </summary>
	[Column("ExecutedAt")]
	public DateTime ExecutedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("ExecutedBy", CanBeNull = false)]
	public string ExecutedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleExecutionLogs_RuleSets
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleSetId), OtherKey = nameof(RuleManagement.RuleSet.Id))]
	public RuleSet RuleSet { get; set; } = null!;
	#endregion
}
