// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

[Table("RuleContextObjects")]
public partial class RuleContextObject
{
	/// <summary>
	/// Unique identifier for this RuleContextObjects record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Unique name of the rule context object.
	/// </summary>
	[Column("ContextName", CanBeNull = false)]
	public string ContextName { get; set; } = null!; // nvarchar(100)

	/// <summary>
	/// Assembly-qualified .NET type name represented by the rule context.
	/// </summary>
	[Column("RuleTypeId", CanBeNull = false)]
	public string RuleTypeId { get; set; } = null!; // nvarchar(255)

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(500)

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool? IsActive { get; set; } // bit

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedDate")]
	public DateTime? CreatedDate { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Value of the LastUpdatedDate field for this RuleContextObjects record.
	/// </summary>
	[Column("LastUpdatedDate")]
	public DateTime? LastUpdatedDate { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleSetContextObjectLinks_RuleContextObjects backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetContextObjectLink.RuleContextObjectId))]
	public IEnumerable<RuleSetContextObjectLink> RuleSetContextObjectLinks { get; set; } = null!;

	/// <summary>
	/// FK_RuleSets_RuleContextObjects backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSet.OutputTypeId))]
	public IEnumerable<RuleSet> RuleSets { get; set; } = null!;
	#endregion
}
