// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

[Table("RuleSets")]
public partial class RuleSet
{
	/// <summary>
	/// Unique identifier for this RuleSets record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Unique name of the rule workflow.
	/// </summary>
	[Column("WorkflowName", CanBeNull = false)]
	public string WorkflowName { get; set; } = null!; // nvarchar(255)

	/// <summary>
	/// JSON definition of the rules in the workflow.
	/// </summary>
	[Column("RuleContent", CanBeNull = false)]
	public string RuleContent { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// Identifier of the related RuleSetContextObjects record.
	/// </summary>
	[Column("OutputDataTypeId")]
	public int OutputDataTypeId { get; set; } // int

	/// <summary>
	/// Indicates whether this record is active and available for use (1) or soft-deleted (0).
	/// </summary>
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(max)

	/// <summary>
	/// Application-managed version string (format YY.QQ.NN) used for optimistic concurrency control and change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleSetExecutionAudits_RuleSets backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetExecutionAudit.RuleSetId))]
	public IEnumerable<RuleSetExecutionAudit> RuleSetExecutionAudits { get; set; } = null!;

	/// <summary>
	/// FK_RuleSetRuleContextObjectLinks_RuleSets backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetRuleContextObjectLink.RuleSetId))]
	public IEnumerable<RuleSetRuleContextObjectLink> RuleSetRuleContextObjectLinks { get; set; } = null!;

	/// <summary>
	/// FK_RuleSets_RuleSetContextObjects
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(OutputDataTypeId), OtherKey = nameof(RuleSetContextObject.Id))]
	public RuleSetContextObject OutputDataType { get; set; } = null!;
	#endregion
}
