// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

public partial class RuleDbContext : DataConnection
{
	public RuleDbContext()
	{
		InitDataContext();
	}

	public RuleDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public RuleDbContext(DataOptions<RuleDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<RuleSetContextObject>         RuleSetContextObjects         => this.GetTable<RuleSetContextObject>();

	public ITable<RuleSetExecutionAudit>        RuleSetExecutionAudits        => this.GetTable<RuleSetExecutionAudit>();

	public ITable<RuleSetRuleContextObjectLink> RuleSetRuleContextObjectLinks => this.GetTable<RuleSetRuleContextObjectLink>();

	public ITable<RuleSet>                      RuleSets                      => this.GetTable<RuleSet>();
}

public static partial class ExtensionMethods
{
	#region Table Extensions
	public static RuleSetContextObject? Find(this ITable<RuleSetContextObject> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<RuleSetContextObject?> FindAsync(this ITable<RuleSetContextObject> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static RuleSetExecutionAudit? Find(this ITable<RuleSetExecutionAudit> table, long id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<RuleSetExecutionAudit?> FindAsync(this ITable<RuleSetExecutionAudit> table, long id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static RuleSetRuleContextObjectLink? Find(this ITable<RuleSetRuleContextObjectLink> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<RuleSetRuleContextObjectLink?> FindAsync(this ITable<RuleSetRuleContextObjectLink> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}

	public static RuleSet? Find(this ITable<RuleSet> table, int id)
	{
		return table.FirstOrDefault(e => e.Id == id);
	}

	public static Task<RuleSet?> FindAsync(this ITable<RuleSet> table, int id, CancellationToken cancellationToken = default)
	{
		return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
	}
	#endregion
}
