// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

/// <summary>
/// Establishes a many-to-many relationship between RuleSets and RuleSetContextObjects,
/// also specifying whether the context object is used as Input or Output.
/// </summary>
[Table("RuleSetRuleContextObjectLinks")]
public partial class RuleSetRuleContextObjectLink
{
	/// <summary>
	/// Unique identifier for this RuleSetRuleContextObjectLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Public identifier used by the UI and external systems (GUID).
	/// </summary>
	[Column("PublicId")]
	public Guid PublicId { get; set; } // uniqueidentifier

	/// <summary>
	/// Identifier of the related RuleSets record.
	/// </summary>
	[Column("RuleSetId")]
	public int RuleSetId { get; set; } // int

	/// <summary>
	/// Whether this context object is used as 'Input' or 'Output' for the rule set.
	/// </summary>
	[Column("InputOrOutputType", CanBeNull = false)]
	public string InputOrOutputType { get; set; } = null!; // nvarchar(50)

	/// <summary>
	/// Identifier of the related RuleSetContextObjects record.
	/// </summary>
	[Column("RuleContextObjectId")]
	public int RuleContextObjectId { get; set; } // int

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime2(3)

	/// <summary>
	/// Identifier of the user who created this record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleSetRuleContextObjectLinks_RuleSetContextObjects
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleContextObjectId), OtherKey = nameof(RuleManagement.RuleSetContextObject.Id))]
	public RuleSetContextObject RuleSetContextObject { get; set; } = null!;

	/// <summary>
	/// FK_RuleSetRuleContextObjectLinks_RuleSets
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleSetId), OtherKey = nameof(RuleManagement.RuleSet.Id))]
	public RuleSet RuleSet { get; set; } = null!;
	#endregion
}

