// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

[Table("RuleSets")]
public partial class RuleSet
{
	/// <summary>
	/// Unique identifier for this RuleSets record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Unique name of the rule workflow.
	/// </summary>
	[Column("WorkflowName", CanBeNull = false)]
	public string WorkflowName { get; set; } = null!; // nvarchar(255)

	/// <summary>
	/// JSON definition of the rules in the workflow.
	/// </summary>
	[Column("RuleContent", CanBeNull = false)]
	public string RuleContent { get; set; } = null!; // nvarchar(max)

	/// <summary>
	/// Identifier of the related RuleContextObjects record.
	/// </summary>
	[Column("OutputTypeId")]
	public int OutputTypeId { get; set; } // int

	/// <summary>
	/// Indicates whether this record is active and available for use.
	/// </summary>
	[Column("IsActive")]
	public bool? IsActive { get; set; } // bit

	/// <summary>
	/// Optional human-readable description of this record.
	/// </summary>
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(500)

	/// <summary>
	/// Application-managed version value used for record change tracking.
	/// </summary>
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the related Users record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleExecutionLogs_RuleSets backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleExecutionLog.RuleSetId))]
	public IEnumerable<RuleExecutionLog> RuleExecutionLogs { get; set; } = null!;

	/// <summary>
	/// FK_RuleSetContextObjectLinks_RuleSets backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(RuleSetContextObjectLink.RuleSetId))]
	public IEnumerable<RuleSetContextObjectLink> RuleSetContextObjectLinks { get; set; } = null!;

	/// <summary>
	/// FK_RuleSets_RuleContextObjects
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(OutputTypeId), OtherKey = nameof(RuleContextObject.Id))]
	public RuleContextObject OutputType { get; set; } = null!;
	#endregion
}
