// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.RuleManagement;

[Table("RuleSetContextObjectLinks")]
public partial class RuleSetContextObjectLink
{
	/// <summary>
	/// Unique identifier for this RuleSetContextObjectLinks record.
	/// </summary>
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int

	/// <summary>
	/// Identifier of the related RuleSets record.
	/// </summary>
	[Column("RuleSetId")]
	public int RuleSetId { get; set; } // int

	/// <summary>
	/// Identifier of the related RuleContextObjects record.
	/// </summary>
	[Column("RuleContextObjectId")]
	public int RuleContextObjectId { get; set; } // int

	/// <summary>
	/// Date and time at which this record was created.
	/// </summary>
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the user who created this record.
	/// </summary>
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	/// <summary>
	/// Date and time at which this record was last updated.
	/// </summary>
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime

	/// <summary>
	/// Identifier of the user who last updated this record.
	/// </summary>
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_RuleSetContextObjectLinks_RuleContextObjects
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleContextObjectId), OtherKey = nameof(RuleManagement.RuleContextObject.Id))]
	public RuleContextObject RuleContextObject { get; set; } = null!;

	/// <summary>
	/// FK_RuleSetContextObjectLinks_RuleSets
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(RuleSetId), OtherKey = nameof(RuleManagement.RuleSet.Id))]
	public RuleSet RuleSet { get; set; } = null!;
	#endregion
}
