// <auto-generated>
// Generated from ActivateServiceOperation
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class ActivateServiceOperationOutput
{
    public int? OperationId { get; set; }
    public string? OperationName { get; set; }
    public string? Message { get; set; }
    public long? AuditActivityId { get; set; }
}