// <auto-generated>
// Generated from CreateServiceApplication
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class CreateServiceApplicationInput
{
    public string ServiceType { get; set; } = default!;
    public Guid? ServiceAppAuthenticationId { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string BaseUrl { get; set; } = default!;
    public string? DefinitionType { get; set; } = default!;
    public string? DefinitionRelativeUrl { get; set; } = default!;
    public string? HealthcheckRelativeUrl { get; set; } = default!;
    public string? Description { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}