// <auto-generated>
// Generated from CreateTestSuiteExecutionAudit
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class CreateTestSuiteExecutionAuditInput
{
    public int ServiceTestSuiteId { get; set; } = default!;
    public string? ExecutionStatus { get; set; } = default!;
    public string? ExecutionDetails { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}