// <auto-generated>
// Generated from GetServiceOperations
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceOperationsInput
{
    public Guid ServiceApplicationPublicId { get; set; } = default!;
    public bool? IncludeInactive { get; set; } = default!;
    public string? OperationName { get; set; } = default!;
}