// <auto-generated>
// Generated from GetSoapNamespaces
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetSoapNamespacesInput
{
    public int? ServiceOperationSchemaId { get; set; } = default!;
    public int? NamespaceId { get; set; } = default!;
    public bool? IncludeContent { get; set; } = default!;
}