// <auto-generated>
// Generated from GetServiceRequestFileChain
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class GetServiceRequestFileChainInput
{
    public int FileId { get; set; } = default!;
    public bool? IncludeData { get; set; } = default!;
}