// <auto-generated>
// Generated from InsertServiceRequestFile
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class InsertServiceRequestFileInput
{
    public int ServiceOperationId { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string? FileFormat { get; set; } = default!;
    public bool? IsBaseSnapshot { get; set; } = default!;
    public int? ParentBaseId { get; set; } = default!;
    public int? ParentDeltaId { get; set; } = default!;
    public byte[]? CompressedData { get; set; } = default!;
    public int? UncompressedSizeBytes { get; set; } = default!;
    public string? CompressionAlgorithmType { get; set; } = default!;
    public string? ContentHash { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}