// <auto-generated>
// Generated from InsertServiceRequestFileEmbedding
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class InsertServiceRequestFileEmbeddingInput
{
    public int ServiceRequestFileId { get; set; } = default!;
    public byte[]? CompressedData { get; set; } = default!;
    public int UncompressedSizeBytes { get; set; } = default!;
    public string CompressionAlgorithmType { get; set; } = default!;
    public string? FileFormat { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}