// <auto-generated>
// Generated from InsertServiceResponseFileEmbedding
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class InsertServiceResponseFileEmbeddingOutput
{
    public int? EmbeddingId { get; set; }
    public int? ServiceResponseFileId { get; set; }
    public int? BinaryEmbeddingsStoreId { get; set; }
    public string? Name { get; set; }
    public string? FileHash { get; set; }
    public bool? IsActive { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public bool? IsExisting { get; set; }
    public long? AuditActivityId { get; set; }
}