// <auto-generated>
// Generated from LinkTestCaseToSuite
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class LinkTestCaseToSuiteOutput
{
    public int? LinkId { get; set; }
    public int? ServiceTestSuiteId { get; set; }
    public int? ServiceTestCaseId { get; set; }
    public int? ExecutionOrder { get; set; }
    public bool? IsActive { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}