// <auto-generated>
// Generated from LinkTestCaseToSuite
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class LinkTestCaseToSuiteInput
{
    public int ServiceTestSuiteId { get; set; } = default!;
    public int ServiceTestCaseId { get; set; } = default!;
    public int? ExecutionOrder { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}