// <auto-generated>
// Generated from UpdateServiceRequestFile
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpdateServiceRequestFileInput
{
    public int FileId { get; set; } = default!;
    public string? Name { get; set; } = default!;
    public string? FileFormat { get; set; } = default!;
    public byte[]? CompressedData { get; set; } = default!;
    public int? UncompressedSizeBytes { get; set; } = default!;
    public string? CompressionAlgorithmType { get; set; } = default!;
    public string? ContentHash { get; set; } = default!;
    public bool? IsActive { get; set; } = default!;
    public string? UserId { get; set; } = default!;
    public string RecordVersion { get; set; } = default!;
}