// <auto-generated>
// Generated from UpdateServiceTestCase
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpdateServiceTestCaseOutput
{
    public int? TestCaseId { get; set; }
    public string? Name { get; set; }
    public int? ServiceRequestFileId { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}