// <auto-generated>
// Generated from UpsertServiceApplication
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpsertServiceApplicationOutput
{
    public int? ServiceApplicationId { get; set; }
    public Guid? PublicId { get; set; }
    public string? Name { get; set; }
    public string? ServiceType { get; set; }
    public string? BaseUrl { get; set; }
    public string? DefinitionType { get; set; }
    public string? DefinitionRelativeUrl { get; set; }
    public string? HealthcheckRelativeUrl { get; set; }
    public string? Description { get; set; }
    public bool? IsActive { get; set; }
    public string? RecordVersion { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public long? AuditActivityId { get; set; }
}