// <auto-generated>
// Generated from UpsertServiceApplication
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.TestManagement.Models;

public class UpsertServiceApplicationInput
{
    public Guid PublicId { get; set; } = default!;
    public string RecordVersion { get; set; } = default!;
    public string? ServiceType { get; set; } = default!;
    public Guid? ServiceAppAuthenticationId { get; set; } = default!;
    public string? Name { get; set; } = default!;
    public string? BaseUrl { get; set; } = default!;
    public string? DefinitionType { get; set; } = default!;
    public string? DefinitionRelativeUrl { get; set; } = default!;
    public string? HealthcheckRelativeUrl { get; set; } = default!;
    public string? Description { get; set; } = default!;
    public string? UserId { get; set; } = default!;
    public bool? IsActive { get; set; } = default!;
    public string? ActivityNotes { get; set; } = default!;
}