// <auto-generated>
// Generated from CreateUserPermission
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.PermissionsManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Models;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Repositories;

public class CreateUserPermissionRepository
{
    private readonly PermissionsDbContext _ctx;

    public CreateUserPermissionRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<CreateUserPermissionOutput>> ExecuteAsync(CreateUserPermissionInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<CreateUserPermissionOutput>(
                    "[dbo].[usp_CreateUserPermission]",
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@ResourcePermissionId", input.ResourcePermissionId),
                new DataParameter("@IsGranted", input.IsGranted),
                new DataParameter("@IsActive", input.IsActive),
                new DataParameter("@CreatedBy", input.CreatedBy)
                )).ToList();
                return RepositoryResult<CreateUserPermissionOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<CreateUserPermissionOutput>.Fail(ex.Message);
        }
    }
}