// <auto-generated>
// Generated from DeleteUserPermission
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.PermissionsManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Models;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Repositories;

public class DeleteUserPermissionRepository
{
    private readonly PermissionsDbContext _ctx;

    public DeleteUserPermissionRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<DeleteUserPermissionOutput>> ExecuteAsync(DeleteUserPermissionInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<DeleteUserPermissionOutput>(
                    "[dbo].[usp_DeleteUserPermission]",
                new DataParameter("@UserPermissionId", input.UserPermissionId),
                new DataParameter("@UserId", input.UserId)
                )).ToList();
                return RepositoryResult<DeleteUserPermissionOutput>.Ok(result.FirstOrDefault()!);
        }
        catch (Exception ex)
        {
            return RepositoryResult<DeleteUserPermissionOutput>.Fail(ex.Message);
        }
    }
}