// <auto-generated>
// Generated from GetRolePermissions
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.PermissionsManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Models;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Repositories;

public class GetRolePermissionsRepository
{
    private readonly PermissionsDbContext _ctx;

    public GetRolePermissionsRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<GetRolePermissionsOutput>>> ExecuteAsync(GetRolePermissionsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<GetRolePermissionsOutput>(
                    "[dbo].[usp_GetRolePermissions]",
                new DataParameter("@RoleId", input.RoleId),
                new DataParameter("@IncludeInactive", input.IncludeInactive)
                )).ToList();
                return RepositoryResult<List<GetRolePermissionsOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<GetRolePermissionsOutput>>.Fail(ex.Message);
        }
    }
}