// <auto-generated>
// Generated from RemoveServiceAppPermissions
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.PermissionsManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Models;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Repositories;

public class RemoveServiceAppPermissionsRepository
{
    private readonly PermissionsDbContext _ctx;

    public RemoveServiceAppPermissionsRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<RemoveServiceAppPermissionsOutput>>> ExecuteAsync(RemoveServiceAppPermissionsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<RemoveServiceAppPermissionsOutput>(
                    "[dbo].[usp_RemoveServiceAppPermissions]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@PermissionKeys", input.PermissionKeys),
                new DataParameter("@CreatedBy", input.CreatedBy)
                )).ToList();
                return RepositoryResult<List<RemoveServiceAppPermissionsOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<RemoveServiceAppPermissionsOutput>>.Fail(ex.Message);
        }
    }
}