// <auto-generated>
// Generated from UpsertServiceAppPermissions
// </auto-generated>
#nullable enable

using LinqToDB;
using LinqToDB.Data;
using OrbitHub.Data.PermissionsManagement;
using OrbitHub.Data.Repositories.Common;
using OrbitHub.Data.Repositories.PermissionsManagement.Models;

namespace OrbitHub.Data.Repositories.PermissionsManagement.Repositories;

public class UpsertServiceAppPermissionsRepository
{
    private readonly PermissionsDbContext _ctx;

    public UpsertServiceAppPermissionsRepository(PermissionsDbContext ctx)
    {
        _ctx = ctx;
    }

    public async Task<RepositoryResult<List<UpsertServiceAppPermissionsOutput>>> ExecuteAsync(UpsertServiceAppPermissionsInput input, CancellationToken ct = default)
    {
        try
        {
                var result = (await _ctx.QueryProcAsync<UpsertServiceAppPermissionsOutput>(
                    "[dbo].[usp_UpsertServiceAppPermissions]",
                new DataParameter("@ServiceApplicationPublicId", input.ServiceApplicationPublicId),
                new DataParameter("@UserId", input.UserId),
                new DataParameter("@PermissionKeys", input.PermissionKeys),
                new DataParameter("@IsGranted", input.IsGranted),
                new DataParameter("@CreatedBy", input.CreatedBy)
                )).ToList();
                return RepositoryResult<List<UpsertServiceAppPermissionsOutput>>.Ok(result);
        }
        catch (Exception ex)
        {
            return RepositoryResult<List<UpsertServiceAppPermissionsOutput>>.Fail(ex.Message);
        }
    }
}