<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\ServiceHubEnterprise.Data\ServiceHubEnterprise.Data.csproj" />
    <ProjectReference Include="..\..\Components\ServiceHubEnterprise.Common\ServiceHubEnterprise.Common.csproj" />
    <ProjectReference Include="..\..\Components\ServiceHubEnterprise.Grid\ServiceHubEnterprise.Grid.csproj" />
    <ProjectReference Include="..\..\Components\ServiceHubEnterprise.Ui\ServiceHubEnterprise.Ui.csproj" />
  </ItemGroup>

</Project>
