// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceAppAuthentications")]
public partial class ServiceAppAuthentication
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("AuthenticationType", CanBeNull = false)]
	public string AuthenticationType { get; set; } = null!; // varchar(50)
	[Column("EncryptionAlgorithmType")]
	public string? EncryptionAlgorithmType { get; set; } // varchar(50)
	[Column("EncryptedCredentialsJson", CanBeNull = false)]
	public string EncryptedCredentialsJson { get; set; } = null!; // nvarchar(max)
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceApplications_ServiceAppAuthentications_AuthenticationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceApplication.ServiceAppAuthenticationId))]
	public IEnumerable<ServiceApplication> ServiceApplications { get; set; } = null!;
	#endregion
}
