// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceRequestFiles")]
public partial class ServiceRequestFile
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("OperationId")]
	public int OperationId { get; set; } // int
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)
	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!; // nvarchar(250)
	[Column("FileData", CanBeNull = false)]
	public byte[] FileData { get; set; } = null!; // varbinary(max)
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_DirectExecutionAuditResponseFileLinks_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(DirectExecutionAuditResponseFileLink.ServiceRequestFileId))]
	public IEnumerable<DirectExecutionAuditResponseFileLink> DirectExecutionAuditResponseFileLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFiles backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFileEmbedding.ServiceRequestFileId))]
	public IEnumerable<ServiceRequestFileEmbedding> ServiceRequestFileEmbeddings { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFileHistorys_ServiceRequestFiles_ServiceRequestFileId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFileHistory.ServiceRequestFileId))]
	public IEnumerable<ServiceRequestFileHistory> ServiceRequestFileHistorys { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFiles_ServiceOperations_OperationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(OperationId), OtherKey = nameof(ServiceOperation.Id))]
	public ServiceOperation Operation { get; set; } = null!;
	#endregion
}
