// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceOperations")]
public partial class ServiceOperation
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("ServiceApplicationId")]
	public int ServiceApplicationId { get; set; } // int
	[Column("OperationName", CanBeNull = false)]
	public string OperationName { get; set; } = null!; // nvarchar(200)
	[Column("EndpointOrAction")]
	public string? EndpointOrAction { get; set; } // nvarchar(500)
	[Column("HttpMethod")]
	public string? HttpMethod { get; set; } // varchar(10)
	[Column("InputRootElementName")]
	public string? InputRootElementName { get; set; } // nvarchar(200)
	[Column("OutputRootElementName")]
	public string? OutputRootElementName { get; set; } // nvarchar(200)
	[Column("Description")]
	public string? Description { get; set; } // nvarchar(max)
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceOperationSchemas_ServiceOperations_OperationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceOperationSchema.OperationId))]
	public IEnumerable<ServiceOperationSchema> ServiceOperationSchemas { get; set; } = null!;

	/// <summary>
	/// FK_ServiceOperations_ServiceApplications_ServiceApplicationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceApplicationId), OtherKey = nameof(TestManagement.ServiceApplication.Id))]
	public ServiceApplication ServiceApplication { get; set; } = null!;

	/// <summary>
	/// FK_ServiceRequestFiles_ServiceOperations_OperationId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceRequestFile.OperationId))]
	public IEnumerable<ServiceRequestFile> ServiceRequestFiles { get; set; } = null!;
	#endregion
}
