// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceOperationSchemas")]
public partial class ServiceOperationSchema
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("DefinitionSyncId")]
	public int DefinitionSyncId { get; set; } // int
	[Column("OperationId")]
	public int? OperationId { get; set; } // int
	[Column("TargetNamespace")]
	public string? TargetNamespace { get; set; } // nvarchar(500)
	[Column("SchemaContent", CanBeNull = false)]
	public string SchemaContent { get; set; } = null!; // nvarchar(max)
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_ServiceOperationSchemas_ServiceDefinitionSync_DefinitionSyncId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(DefinitionSyncId), OtherKey = nameof(ServiceDefinitionSync.Id))]
	public ServiceDefinitionSync DefinitionSync { get; set; } = null!;

	/// <summary>
	/// FK_ServiceOperationSchemas_ServiceOperations_OperationId
	/// </summary>
	[Association(ThisKey = nameof(OperationId), OtherKey = nameof(ServiceOperation.Id))]
	public ServiceOperation? Operation { get; set; }

	/// <summary>
	/// FK_SoapNamespaces_ServiceOperationSchemas_ServiceOperationSchemaId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(SoapNamespace.ServiceOperationSchemaId))]
	public IEnumerable<SoapNamespace> SoapNamespaces { get; set; } = null!;
	#endregion
}
