// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceDefinitionSyncHistorys")]
public partial class ServiceDefinitionSyncHistory
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public long Id { get; set; } // bigint
	[Column("ServiceDefinitionSyncId")]
	public int ServiceDefinitionSyncId { get; set; } // int
	[Column("ServiceApplicationId")]
	public int ServiceApplicationId { get; set; } // int
	[Column("DefinitionUrl")]
	public string? DefinitionUrl { get; set; } // nvarchar(500)
	[Column("DefinitionContent", CanBeNull = false)]
	public byte[] DefinitionContent { get; set; } = null!; // varbinary(max)
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)
	[Column("RecordVersion", CanBeNull = false)]
	public string RecordVersion { get; set; } = null!; // varchar(50)
	[Column("SyncedAt")]
	public DateTime SyncedAt { get; set; } // datetime
	[Column("SyncedBy", CanBeNull = false)]
	public string SyncedBy { get; set; } = null!; // nvarchar(20)
	[Column("ChangedAt")]
	public DateTime ChangedAt { get; set; } // datetime
	[Column("ChangedBy", CanBeNull = false)]
	public string ChangedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceDefinitionSyncHistorys_ServiceApplications_ServiceApplicationId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceApplicationId), OtherKey = nameof(TestManagement.ServiceApplication.Id))]
	public ServiceApplication ServiceApplication { get; set; } = null!;

	/// <summary>
	/// FK_ServiceDefinitionSyncHistorys_ServiceDefinitionSyncs_ServiceDefinitionSyncId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceDefinitionSyncId), OtherKey = nameof(TestManagement.ServiceDefinitionSync.Id))]
	public ServiceDefinitionSync ServiceDefinitionSync { get; set; } = null!;
	#endregion
}
