// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceRequestFileEmbeddings")]
public partial class ServiceRequestFileEmbedding
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("ServiceRequestFileId")]
	public int? ServiceRequestFileId { get; set; } // int
	[Column("ServiceRequestFileHistoryId")]
	public int? ServiceRequestFileHistoryId { get; set; } // int
	[Column("FileFormat")]
	public string? FileFormat { get; set; } // varchar(10)
	[Column("FileName", CanBeNull = false)]
	public string FileName { get; set; } = null!; // nvarchar(250)
	[Column("FileData", CanBeNull = false)]
	public byte[] FileData { get; set; } = null!; // varbinary(max)
	[Column("UncompressedSizeBytes")]
	public int? UncompressedSizeBytes { get; set; } // int
	[Column("CompressionAlgorithmType")]
	public string? CompressionAlgorithmType { get; set; } // varchar(50)
	[Column("FileHash")]
	public string? FileHash { get; set; } // varchar(64)
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime

	#region Associations
	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFileHistorys
	/// </summary>
	[Association(ThisKey = nameof(ServiceRequestFileHistoryId), OtherKey = nameof(TestManagement.ServiceRequestFileHistory.Id))]
	public ServiceRequestFileHistory? ServiceRequestFileHistory { get; set; }

	/// <summary>
	/// FK_ServiceRequestFileEmbeddings_ServiceRequestFiles
	/// </summary>
	[Association(ThisKey = nameof(ServiceRequestFileId), OtherKey = nameof(TestManagement.ServiceRequestFile.Id))]
	public ServiceRequestFile? ServiceRequestFile { get; set; }
	#endregion
}
