// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceTestSuitTestCaseLinks")]
public partial class ServiceTestSuitTestCaseLink
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("ServiceTestSuiteId")]
	public int ServiceTestSuiteId { get; set; } // int
	[Column("ServiceTestCaseId")]
	public int ServiceTestCaseId { get; set; } // int
	[Column("ExecutionOrder")]
	public int ExecutionOrder { get; set; } // int
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestSuitTestCaseLinks_ServiceTestCases_ServiceTestCaseId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestCaseId), OtherKey = nameof(TestManagement.ServiceTestCase.Id))]
	public ServiceTestCase ServiceTestCase { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuitTestCaseLinks_ServiceTestSuites_ServiceTestSuiteId
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(ServiceTestSuiteId), OtherKey = nameof(TestManagement.ServiceTestSuite.Id))]
	public ServiceTestSuite ServiceTestSuite { get; set; } = null!;
	#endregion
}
