// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace ServiceHubEnterprise.Data.TestManagement;

[Table("ServiceTestCases")]
public partial class ServiceTestCase
{
	[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
	public int Id { get; set; } // int
	[Column("Name", CanBeNull = false)]
	public string Name { get; set; } = null!; // nvarchar(200)
	[Column("ServiceRequestFileId")]
	public int ServiceRequestFileId { get; set; } // int
	[Column("IsActive")]
	public bool IsActive { get; set; } // bit
	[Column("CreatedAt")]
	public DateTime CreatedAt { get; set; } // datetime
	[Column("CreatedBy", CanBeNull = false)]
	public string CreatedBy { get; set; } = null!; // nvarchar(20)
	[Column("LastUpdatedAt")]
	public DateTime? LastUpdatedAt { get; set; } // datetime
	[Column("LastUpdatedBy")]
	public string? LastUpdatedBy { get; set; } // nvarchar(20)

	#region Associations
	/// <summary>
	/// FK_ServiceTestCaseRuleSetLinks_ServiceTestCases_ServiceTestCaseId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestCaseRuleSetLink.ServiceTestCaseId))]
	public IEnumerable<ServiceTestCaseRuleSetLink> ServiceTestCaseRuleSetLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestExecutionAuditTestSuitLinks_ServiceTestCases_ServiceTestCaseId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestExecutionAuditTestSuitLink.ServiceTestCaseId))]
	public IEnumerable<ServiceTestExecutionAuditTestSuitLink> ServiceTestExecutionAuditTestSuitLinks { get; set; } = null!;

	/// <summary>
	/// FK_ServiceTestSuitTestCaseLinks_ServiceTestCases_ServiceTestCaseId backreference
	/// </summary>
	[Association(ThisKey = nameof(Id), OtherKey = nameof(ServiceTestSuitTestCaseLink.ServiceTestCaseId))]
	public IEnumerable<ServiceTestSuitTestCaseLink> ServiceTestSuitTestCaseLinks { get; set; } = null!;
	#endregion
}
