// <auto-generated>
// Generated from v_ServiceAppPermissionsWithDetails
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Views;

public class ServiceAppPermissionsWithDetailsView
{
    public long PermissionId { get; set; }
    public string PermissionPublicId { get; set; } = string.Empty;
    public bool IsGranted { get; set; }
    public DateTime PermissionCreatedAt { get; set; }
    public string PermissionCreatedBy { get; set; } = string.Empty;
    public DateTime? PermissionLastUpdatedAt { get; set; }
    public string? PermissionLastUpdatedBy { get; set; }
    public string ServicePublicId { get; set; } = string.Empty;
    public long ServiceInternalId { get; set; }
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceType { get; set; } = string.Empty;
    public string? BaseUrl { get; set; }
    public int? ServiceVersion { get; set; }
    public bool? ServiceIsActive { get; set; }
    public string UserId { get; set; } = string.Empty;
    public string UserFullName { get; set; } = string.Empty;
    public string UserEmail { get; set; } = string.Empty;
    public string? UserDepartment { get; set; }
    public string PermissionKey { get; set; } = string.Empty;
    public long ResourcePermissionId { get; set; }
    public string ResourcePermissionPublicId { get; set; } = string.Empty;
    public string PermissionStatus { get; set; } = string.Empty;
    public string PermissionCategory { get; set; } = string.Empty;
    public string PermissionAction { get; set; } = string.Empty;
    public string PermissionDisplayName { get; set; } = string.Empty;
}
