// <auto-generated>
// Generated from v_UserPermissionsSummary
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Views;

public class UserPermissionsSummaryView
{
    public string UserId { get; set; } = string.Empty;
    public string UserFullName { get; set; } = string.Empty;
    public string UserEmail { get; set; } = string.Empty;
    public string? UserDepartment { get; set; }
    public int TotalServiceAccess { get; set; }
    public int TotalPermissionTypes { get; set; }
    public int GrantedServiceAccess { get; set; }
    public int DeniedServiceAccess { get; set; }
    public string? GrantedPermissions { get; set; }
    public string? AccessibleServices { get; set; }
    public DateTime? LastPermissionUpdate { get; set; }
    public string? LastPermissionUpdater { get; set; }
}
