// <auto-generated>
// Generated from BinaryEmbeddingExists
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.IndexingManagement.Models;

public class BinaryEmbeddingExistsInput
{
    public string ContentHash { get; set; } = default!;
}
