// <auto-generated>
// Generated from GetBinaryEmbeddingById
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.IndexingManagement.Models;

public class GetBinaryEmbeddingByIdInput
{
    public int EmbeddingId { get; set; } = default!;
    public bool? IncludeData { get; set; } = default!;
}