// <auto-generated>
// Generated from GetBinaryEmbeddingUsage
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.IndexingManagement.Models;

public class GetBinaryEmbeddingUsageInput
{
    public string FileHash { get; set; } = default!;
}