// <auto-generated>
// Generated from GetElementFrequency
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Models;

public class GetElementFrequencyInput
{
    public string? ElementType { get; set; } = default!;
    public int? MinFrequency { get; set; } = default!;
}