// <auto-generated>
// Generated from GetIndexingStatistics
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Models;

public class GetIndexingStatisticsOutput
{
    public string? ElementType { get; set; }
    public int? UniqueElements { get; set; }
    public int? TotalMappings { get; set; }
    public int? RequestFiles { get; set; }
    public int? ResponseFiles { get; set; }
    public int? RequestCompleted { get; set; }
    public int? RequestPending { get; set; }
    public int? RequestFailed { get; set; }
    public int? ResponseCompleted { get; set; }
    public int? ResponsePending { get; set; }
    public int? ResponseFailed { get; set; }
}