// <auto-generated>
// Generated from GetIndexingStatistics
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Models;

public class GetIndexingStatisticsInput
{
}