// <auto-generated>
// Generated from InsertBinaryEmbedding
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.IndexingManagement.Models;

public class InsertBinaryEmbeddingOutput
{
    public int? EmbeddingId { get; set; }
    public string? FileHash { get; set; }
    public byte[]? CompressedData { get; set; }
    public int? UncompressedSizeBytes { get; set; }
    public string? CompressionAlgorithmType { get; set; }
    public string? FileFormat { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime? LastUpdatedAt { get; set; }
    public string? LastUpdatedBy { get; set; }
    public bool? IsNew { get; set; }
}