// <auto-generated>
// Generated from GetRolePermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class GetRolePermissionsInput
{
    public int? RoleId { get; set; } = default!;
    public bool? IncludeInactive { get; set; } = default!;
}