// <auto-generated>
// Generated from GetServiceAppPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class GetServiceAppPermissionsInput
{
    public Guid ServiceApplicationPublicId { get; set; } = default!;
    public string? UserId { get; set; } = default!;
}