// <auto-generated>
// Generated from RemoveServiceAppPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class RemoveServiceAppPermissionsInput
{
    public Guid ServiceApplicationPublicId { get; set; } = default!;
    public string UserId { get; set; } = default!;
    public string? PermissionKeys { get; set; } = default!;
    public string? CreatedBy { get; set; } = default!;
}