// <auto-generated>
// Generated from UpsertServiceAppPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class UpsertServiceAppPermissionsOutput
{
    public long? PermissionId { get; set; }
    public Guid? PermissionPublicId { get; set; }
    public string? UserId { get; set; }
    public string? UserFullName { get; set; }
    public string? UserEmail { get; set; }
    public bool? IsGranted { get; set; }
    public string? PermissionKey { get; set; }
    public long? ResourcePermissionId { get; set; }
    public DateTime? PermissionCreatedAt { get; set; }
    public string? PermissionCreatedBy { get; set; }
    public DateTime? PermissionLastUpdatedAt { get; set; }
    public string? PermissionLastUpdatedBy { get; set; }
    public Guid? ServicePublicId { get; set; }
    public string? ServiceName { get; set; }
    public string? ServiceVersion { get; set; }
}