// <auto-generated>
// Generated from UpsertServiceAppPermissions
// </auto-generated>
#nullable enable

namespace OrbitHub.Data.Repositories.PermissionsManagement.Models;

public class UpsertServiceAppPermissionsInput
{
    public Guid ServiceApplicationPublicId { get; set; } = default!;
    public string UserId { get; set; } = default!;
    public string PermissionKeys { get; set; } = default!;
    public bool? IsGranted { get; set; } = default!;
    public string? CreatedBy { get; set; } = default!;
}