// <auto-generated>
// Generated by Repository DI registration
// </auto-generated>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using LinqToDB.Data;
using OrbitHub.Data.TestManagement;
using OrbitHub.Data.CoreManagement.Repositories;
using OrbitHub.Data.ServiceAppManagement.Repositories;
using OrbitHub.Data.Common;

namespace OrbitHub.Data;

/// <summary>
/// Registers all stored procedure repository classes with the DI container.
/// </summary>
public static class RepositoryRegistration
{
    public static IServiceCollection AddRepositories(this IServiceCollection services)
    {
        // CoreManagement
        services.AddScoped<UpdateUserSettingRepository>();

        // ServiceAppManagement
        services.AddScoped<SaveServiceRequestFileRepository>();

        // UnitOfWork
        services.AddScoped<IUnitOfWork>(sp =>
        {
            var ctx = sp.GetRequiredService<TestDbContext>();
            var logger = sp.GetService<Microsoft.Extensions.Logging.ILogger<UnitOfWork>>();
            return new UnitOfWork((DataConnection)ctx, logger);
        });

        return services;
    }
}