// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated to support the ServiceHub File Version management feature.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace OrbitHub.Data.FileVersionManagement;

public partial class FileManagementDbContext : DataConnection
{
	public FileManagementDbContext()
	{
		InitDataContext();
	}

	public FileManagementDbContext(string configuration)
		: base(configuration)
	{
		InitDataContext();
	}

	public FileManagementDbContext(DataOptions<FileManagementDbContext> options)
		: base(options.Options)
	{
		InitDataContext();
	}

	partial void InitDataContext();

	public ITable<FileVersionEntity> FileVersions => this.GetTable<FileVersionEntity>();
}